/**
 * Customer Responsibility Matrix (CRM) for CMMC Level 2
 * Microsoft 365 GCC High at G5 license level
 *
 * Source: Microsoft Product Placemat for CMMC Preview Sept 2024, GCCH at G5 level
 *
 * Defines the shared-responsibility model between Microsoft and the customer
 * for each NIST SP 800-171 Rev 2 control.
 *
 * Tier definitions:
 *   "Inherited" = Microsoft GCC High infrastructure handles it
 *   "Shared"    = Microsoft provides tooling, customer must configure/operate
 *   "Company"   = Entirely customer-owned (no significant MS tooling)
 *
 * Keyed by Rev 2 control ID (3.x.x) for compatibility with the app's control data.
 *
 * Service name conventions (admin-center-level):
 *   Entra ID, Intune, Defender, Purview, Sentinel,
 *   Azure RBAC, PIM, Teams, Exchange Admin Center
 *
 * Total entries: 110 controls across 14 domains
 *
 * Generated by: Policy or Config enrichment pipeline
 * Integration date: 2026-03-18
 */

export type ResponsibilityTier = "Inherited" | "Shared" | "Company";

export interface ControlCrm {
  /** Responsibility tier */
  tier: ResponsibilityTier;
  /** Simplified Microsoft service names (max 4-5) */
  services: string[];
  /** What Microsoft handles in GCC High */
  microsoftCovers: string;
  /** What the customer organization must do */
  customerOwns: string;
  /** Plain-English popover text for non-technical business owners (~40-60 words) */
  summary: string;
}

/**
 * Standard CRM disclaimer for all popovers.
 * Line 1: scope statement (GCCH / G5)
 * Line 2: residual-responsibility safe harbor (C3PAO-tested language)
 *
 * In the UI, replace {Organization Name} with the tenant's org name at render time.
 */
export const crmDisclaimer = [
  "Based on Microsoft 365 GCC High at the G5 license level. Verify current coverage in the Microsoft Service Trust Portal.",
  "{Organization Name} retains responsibility for all requirements not explicitly inherited by Microsoft.",
];

export const crmData: Record<string, ControlCrm> = {
  // ═══════════════════════════════════════════════════════════════════════════
  // 3.1 — ACCESS CONTROL (22 controls)
  // ═══════════════════════════════════════════════════════════════════════════

  "3.1.1": {
    tier: "Shared",
    services: ["Entra ID", "Intune", "Azure RBAC"],
    microsoftCovers:
      "Entra ID provides identity management, authentication, and conditional access enforcement in GCC High. Intune manages device compliance and enrollment gating.",
    customerOwns:
      "Define and document authorized users, roles, and devices. Configure Entra ID conditional access policies and Intune compliance requirements to match your access control policy.",
    summary:
      "Microsoft gives you the tools to control who can log in and from what devices, but you decide who gets access and under what conditions. You need to maintain a list of authorized users and roles, and set up the rules in Entra ID and Intune that enforce your decisions.",
  },

  "3.1.2": {
    tier: "Shared",
    services: ["Entra ID", "Azure RBAC", "PIM"],
    microsoftCovers:
      "Entra ID and Azure RBAC provide granular role-based permissions and transaction-level access controls. PIM enables just-in-time privileged access activation in GCC High.",
    customerOwns:
      "Define which roles can perform which transactions. Configure RBAC role assignments and PIM activation policies to restrict users to only the functions their job requires.",
    summary:
      "Microsoft provides the permission system that controls what each person can do inside your environment. Your job is to define those roles and map them to actual job functions so that people can only perform the specific actions they need — nothing more.",
  },

  "3.1.3": {
    tier: "Shared",
    services: ["Entra ID", "Intune", "Defender", "Purview"],
    microsoftCovers:
      "Conditional access policies, Defender for Cloud Apps session controls, and Purview sensitivity labels enforce CUI flow boundaries. Network-level controls via Azure Firewall and NSGs segment traffic in GCC High.",
    customerOwns:
      "Classify CUI data and apply sensitivity labels. Configure conditional access and DLP policies to prevent CUI from flowing to unauthorized users, devices, or external locations.",
    summary:
      "Microsoft provides labeling, firewall, and policy tools to control where sensitive data can travel. You need to identify which data is CUI, label it appropriately, and configure the rules that prevent it from leaving your approved boundaries.",
  },

  "3.1.4": {
    tier: "Inherited",
    services: ["Entra ID", "Intune", "Purview"],
    microsoftCovers:
      "Conditional access and Purview information barriers enforce separation of duties at the platform level. Entra ID supports mutually exclusive role assignments in GCC High.",
    customerOwns:
      "Identify conflicting duties within your organization and document separation requirements. Verify that role assignments in Entra ID reflect those separations.",
    summary:
      "Microsoft's platform can enforce rules that keep certain roles separate — like preventing the same person from both approving and processing payments. You need to identify which duties in your organization must be separated and verify your role assignments reflect that.",
  },

  "3.1.5": {
    tier: "Shared",
    services: ["Azure RBAC", "PIM", "Purview"],
    microsoftCovers:
      "Azure RBAC provides fine-grained permission scoping and PIM enforces time-limited, approval-based privilege elevation in GCC High. Purview supports data-level access restrictions.",
    customerOwns:
      "Review all role assignments to ensure users have only the minimum permissions needed. Enable PIM for privileged roles and conduct periodic access reviews.",
    summary:
      "Microsoft gives you a permission system that supports very precise access levels and time-limited admin rights. You need to actually review who has what access, trim anything excessive, and make sure privileged roles require approval and expire automatically.",
  },

  "3.1.6": {
    tier: "Shared",
    services: ["Entra ID", "Azure RBAC"],
    microsoftCovers:
      "Entra ID supports separate privileged and non-privileged accounts with distinct sign-in policies. Azure RBAC enforces role separation across admin and standard accounts in GCC High.",
    customerOwns:
      "Require administrators to use dedicated privileged accounts for admin tasks and separate non-privileged accounts for daily work like email and browsing.",
    summary:
      "Microsoft lets you create separate accounts for admin work and everyday tasks. You need to enforce a policy that admins use their regular account for email and web browsing, and only switch to their privileged account when performing actual admin duties.",
  },

  "3.1.7": {
    tier: "Shared",
    services: ["Entra ID", "Azure RBAC"],
    microsoftCovers:
      "Azure RBAC and Entra ID enforce role-based restrictions that block non-privileged accounts from executing administrative functions in GCC High.",
    customerOwns:
      "Verify that standard user accounts cannot access admin portals or run privileged commands. Test and audit role assignments to confirm non-admin users are properly restricted.",
    summary:
      "Microsoft blocks standard users from admin functions by default through its role system. Your responsibility is to verify this is working — make sure no regular user accounts have been accidentally granted admin-level permissions or access to management portals.",
  },

  "3.1.8": {
    tier: "Inherited",
    services: ["Entra ID"],
    microsoftCovers:
      "Entra ID Smart Lockout automatically limits failed logon attempts by locking accounts after a threshold and using intelligent detection to avoid locking out legitimate users in GCC High.",
    customerOwns:
      "Review Smart Lockout default settings and confirm they meet your security policy. Document the lockout thresholds in your access control policy.",
    summary:
      "Microsoft automatically locks accounts after too many bad password attempts using its Smart Lockout feature — this works out of the box. You just need to review the default settings to make sure the thresholds align with your policy and document them.",
  },

  "3.1.9": {
    tier: "Shared",
    services: ["Entra ID", "Intune"],
    microsoftCovers:
      "Entra ID supports custom sign-in page branding and terms-of-use prompts. Intune can push compliance messages to managed devices in GCC High.",
    customerOwns:
      "Create and configure login banners, terms-of-use agreements, and privacy notices. Ensure all users see required legal and security notices before accessing the system.",
    summary:
      "Microsoft lets you display custom banners and notices on the login screen and require users to accept terms before signing in. You need to write those notices — covering privacy, security, and acceptable use — and configure them in Entra ID.",
  },

  "3.1.10": {
    tier: "Shared",
    services: ["Entra ID", "Intune", "Defender"],
    microsoftCovers:
      "Entra ID enforces session timeouts and re-authentication requirements. Intune pushes screen lock policies to managed devices. Defender for Cloud Apps can enforce session controls in GCC High.",
    customerOwns:
      "Define session lock timeout values in your security policy. Configure Intune device profiles to enforce screen lock after inactivity and require authentication to unlock.",
    summary:
      "Microsoft provides the mechanisms to lock screens and end idle sessions automatically. You need to decide how long someone can be inactive before their screen locks, then configure those timeout values in Intune and Entra ID to enforce it across all devices.",
  },

  "3.1.11": {
    tier: "Shared",
    services: ["Entra ID"],
    microsoftCovers:
      "Entra ID supports configurable session lifetime policies and automatic token expiration for web and application sessions in GCC High.",
    customerOwns:
      "Define acceptable session durations in your security policy. Configure Entra ID session lifetime and conditional access policies to terminate sessions after the defined period.",
    summary:
      "Microsoft can automatically end user sessions after a set amount of time. You decide what those time limits should be based on your security policy, then configure Entra ID's session lifetime settings to enforce automatic logoff when sessions run too long.",
  },

  "3.1.12": {
    tier: "Shared",
    services: ["Intune", "Entra ID", "Defender"],
    microsoftCovers:
      "Intune enforces VPN profiles and compliance requirements on remote devices. Entra ID conditional access can restrict remote sessions based on device state and location in GCC High.",
    customerOwns:
      "Define remote access policies including approved connection methods. Configure Intune VPN profiles and conditional access rules to monitor and control remote session behavior.",
    summary:
      "Microsoft gives you tools to manage how people connect remotely — VPN enforcement, device checks, and location-based rules. You need to define which remote access methods are approved and configure Intune and Entra ID to enforce those requirements.",
  },

  "3.1.13": {
    tier: "Shared",
    services: ["Intune", "Azure RBAC", "Entra ID"],
    microsoftCovers:
      "GCC High encrypts all remote connections via TLS 1.2+ by default. Azure Bastion and VPN Gateway provide encrypted administrative access channels. Intune enforces VPN and encryption profiles on endpoints.",
    customerOwns:
      "Ensure all remote access uses approved encrypted protocols. Configure Intune VPN profiles with required encryption standards and disable any unencrypted remote access methods.",
    summary:
      "Microsoft encrypts remote connections by default using strong protocols across GCC High. Your job is to make sure no one can bypass that encryption — configure VPN profiles through Intune and disable any legacy or unencrypted remote access methods.",
  },

  "3.1.14": {
    tier: "Shared",
    services: ["Entra ID", "Azure RBAC"],
    microsoftCovers:
      "All access to Microsoft 365 and Azure in GCC High routes through Entra ID as the central authentication gateway. Azure management goes through the Azure Portal as a managed access control point.",
    customerOwns:
      "Ensure all remote access routes through your defined access control points. Disable direct access paths that bypass Entra ID and configure conditional access to enforce controlled entry.",
    summary:
      "Microsoft routes all cloud access through Entra ID as a central checkpoint. You need to make sure there are no back doors — disable any direct access paths that could bypass your authentication gateway, and use conditional access to enforce the single entry point.",
  },

  "3.1.15": {
    tier: "Inherited",
    services: ["Entra ID", "PIM"],
    microsoftCovers:
      "Entra ID conditional access and PIM enforce authorization requirements for all remote privileged access in GCC High, including approval workflows and time-limited elevation.",
    customerOwns:
      "Define which remote operations require additional authorization. Configure PIM approval workflows and conditional access policies to match your remote execution authorization requirements.",
    summary:
      "Microsoft provides approval-based privileged access through PIM so that sensitive remote operations require explicit authorization. You need to define which operations require extra approval and configure the PIM workflows so the right people are approving the right actions.",
  },

  "3.1.16": {
    tier: "Shared",
    services: ["Intune", "Entra ID"],
    microsoftCovers:
      "Intune can push Wi-Fi configuration profiles and enforce network compliance on managed devices in GCC High. Entra ID conditional access can gate access based on network location.",
    customerOwns:
      "Define approved wireless networks and authorization requirements. Configure Intune Wi-Fi profiles to restrict connections to authorized networks and disable auto-connect to unknown networks.",
    summary:
      "Microsoft lets you push approved Wi-Fi settings to devices and block access from untrusted networks. You need to define which wireless networks are authorized and configure Intune to only allow connections to those approved networks.",
  },

  "3.1.17": {
    tier: "Shared",
    services: ["Intune", "Entra ID"],
    microsoftCovers:
      "Intune enforces Wi-Fi profile configurations including WPA2/WPA3 encryption and certificate-based authentication on managed devices in GCC High.",
    customerOwns:
      "Require WPA2 Enterprise or stronger encryption on all wireless networks. Configure Intune Wi-Fi profiles with certificate-based authentication and disable connections to open or weakly encrypted networks.",
    summary:
      "Microsoft lets you enforce Wi-Fi encryption and authentication standards through Intune device profiles. You need to configure those profiles to require strong encryption like WPA2 Enterprise and block any connections to open or poorly secured wireless networks.",
  },

  "3.1.18": {
    tier: "Shared",
    services: ["Intune", "Entra ID", "Defender"],
    microsoftCovers:
      "Intune provides mobile device management including enrollment, compliance policies, and app protection in GCC High. Defender for Endpoint extends threat protection to mobile devices.",
    customerOwns:
      "Define your mobile device policy — which devices are allowed, what compliance standards apply, and what happens to non-compliant devices. Enroll devices in Intune and configure compliance rules.",
    summary:
      "Microsoft provides full mobile device management through Intune — enrollment, compliance checks, and threat protection. You need to define which mobile devices can connect, what security standards they must meet, and configure Intune to block non-compliant devices.",
  },

  "3.1.19": {
    tier: "Shared",
    services: ["Intune", "Purview"],
    microsoftCovers:
      "Intune enforces device encryption policies including BitLocker and FileVault on managed devices. Purview sensitivity labels can enforce encryption on CUI documents in GCC High.",
    customerOwns:
      "Enable and verify device encryption on all mobile devices through Intune compliance policies. Apply Purview sensitivity labels to CUI documents to ensure they remain encrypted at rest and in transit.",
    summary:
      "Microsoft provides encryption tools for both devices and documents through Intune and Purview. You need to turn on device encryption requirements in Intune and apply sensitivity labels to CUI so it stays encrypted whether it is sitting on a phone or being emailed.",
  },

  "3.1.20": {
    tier: "Shared",
    services: ["Entra ID", "Azure RBAC", "Defender"],
    microsoftCovers:
      "Entra ID external collaboration settings and conditional access control connections to and from external systems. Defender for Cloud Apps monitors third-party app connections in GCC High.",
    customerOwns:
      "Inventory all external system connections and authorize them. Configure Entra ID external collaboration policies and conditional access to restrict connections to approved external systems only.",
    summary:
      "Microsoft lets you control which outside systems and organizations can connect to yours. You need to maintain a list of approved external connections, configure Entra ID to block unauthorized ones, and periodically review whether those external relationships are still needed.",
  },

  "3.1.21": {
    tier: "Shared",
    services: ["Intune", "Defender"],
    microsoftCovers:
      "Intune device configuration profiles can block or restrict USB and removable storage on managed endpoints. Defender for Endpoint provides device control policies in GCC High.",
    customerOwns:
      "Define your portable storage policy — whether USB drives are blocked, restricted, or allowed. Configure Intune and Defender for Endpoint device control policies to enforce those restrictions.",
    summary:
      "Microsoft gives you the ability to block or restrict USB drives and other portable storage through Intune and Defender. You need to decide your policy — typically blocking USB storage entirely — and configure the device control rules to enforce it across all managed endpoints.",
  },

  "3.1.22": {
    tier: "Inherited",
    services: ["Azure RBAC", "Entra ID", "Purview", "Sentinel"],
    microsoftCovers:
      "Azure RBAC restricts who can publish to public-facing systems. Purview DLP policies can detect and block CUI from being posted to public locations. Sentinel monitors for anomalous data exposure in GCC High.",
    customerOwns:
      "Define policies prohibiting CUI on publicly accessible systems. Configure Purview DLP rules to detect CUI in outbound channels and review Sentinel alerts for potential public exposure.",
    summary:
      "Microsoft provides DLP tools that can catch CUI before it reaches public systems, and Sentinel watches for suspicious data exposure. You need clear policies that prohibit posting CUI publicly, DLP rules configured to enforce that, and someone reviewing alerts when violations occur.",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 3.2 — AWARENESS & TRAINING (3 controls)
  // ═══════════════════════════════════════════════════════════════════════════

  "3.2.1": {
    tier: "Shared",
    services: ["Entra ID", "Defender", "Teams"],
    microsoftCovers:
      "Defender XDR provides attack simulation training and phishing campaign tools. Teams enables training delivery. Entra ID logs training-related sign-in activity in GCC High.",
    customerOwns:
      "Develop and deliver a security awareness training program covering your policies, CUI handling, and threat recognition. Track completion and ensure all users complete training on schedule.",
    summary:
      "Microsoft provides phishing simulations and a platform to deliver training through Defender and Teams, but the actual training program is yours to build. You need to create content covering your security policies, run it regularly, and track that every employee completes it.",
  },

  "3.2.2": {
    tier: "Shared",
    services: ["Defender", "Teams"],
    microsoftCovers:
      "Defender for Office 365 provides safe links and attachment scanning that complements CUI-handling training. Microsoft Learn offers baseline security training content in GCC High.",
    customerOwns:
      "Create and maintain role-based training on CUI identification, handling, marking, and destruction. Ensure all personnel who handle CUI complete this training before access is granted.",
    summary:
      "Microsoft offers some general security training resources and email protection tools, but training your people on how to properly handle CUI is entirely your responsibility. You must build role-specific training covering CUI rules and ensure everyone completes it before they touch CUI.",
  },

  "3.2.3": {
    tier: "Shared",
    services: ["Defender", "Purview", "Teams"],
    microsoftCovers:
      "Defender XDR and Purview Insider Risk Management provide indicators and analytics that support insider threat programs. Teams enables training delivery in GCC High.",
    customerOwns:
      "Develop insider threat awareness training covering indicators, reporting procedures, and organizational policies. Deliver the training to all personnel and maintain completion records.",
    summary:
      "Microsoft provides insider threat detection tools through Defender and Purview that can spot risky behavior, but teaching your people to recognize and report insider threats is your job. Build training that covers warning signs, reporting channels, and your organization's policies.",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 3.3 — AUDIT & ACCOUNTABILITY (9 controls)
  // ═══════════════════════════════════════════════════════════════════════════

  "3.3.1": {
    tier: "Shared",
    services: ["Sentinel", "Entra ID", "Defender", "Intune"],
    microsoftCovers:
      "Entra ID, Defender XDR, Intune, and Defender for Cloud generate audit logs natively. Sentinel and Log Analytics aggregate and retain logs in GCC High with configurable retention periods.",
    customerOwns:
      "Define which events must be logged and how long logs are retained. Configure Sentinel workspaces, connect all log sources, and set retention policies that meet CMMC requirements.",
    summary:
      "Microsoft generates audit logs from every major service — Entra ID, Defender, Intune — and Sentinel collects them all in one place. You need to make sure all log sources are connected, retention periods meet your policy requirements, and nothing important is falling through the cracks.",
  },

  "3.3.2": {
    tier: "Shared",
    services: ["Sentinel", "Entra ID"],
    microsoftCovers:
      "Entra ID associates all actions with individual user identities. Sentinel correlates events across services to individual accounts in GCC High.",
    customerOwns:
      "Prohibit shared or generic accounts so every action traces to a specific person. Ensure naming conventions and account policies support individual accountability in audit logs.",
    summary:
      "Microsoft ties every action in your environment to an individual user identity through Entra ID, and Sentinel links those actions across all your services. Your job is to eliminate shared accounts and ensure every person has their own unique login so audit trails are meaningful.",
  },

  "3.3.3": {
    tier: "Inherited",
    services: ["Sentinel", "Entra ID", "Intune", "Defender"],
    microsoftCovers:
      "Sentinel provides built-in analytics rules and detection templates that are regularly updated by Microsoft. Entra ID, Intune, and Defender logs are automatically available for review in GCC High.",
    customerOwns:
      "Periodically review which events are being logged and update your logging configuration as threats evolve. Enable new Sentinel analytics rules as they become available.",
    summary:
      "Microsoft continuously updates its detection rules and log sources across Sentinel, Entra ID, and Defender. You need to periodically review your logging setup to make sure you are capturing the right events and enabling new detection rules as Microsoft releases them.",
  },

  "3.3.4": {
    tier: "Shared",
    services: ["Sentinel"],
    microsoftCovers:
      "Sentinel supports health monitoring and diagnostic alerts that detect when log ingestion stops or connectors fail in GCC High.",
    customerOwns:
      "Configure Sentinel health alerts to notify your team when log collection fails. Define who receives alerts and establish response procedures for logging failures.",
    summary:
      "Microsoft built health monitoring into Sentinel that can detect when log collection breaks or a connector goes offline. You need to turn on those health alerts, point them at the right people, and have a plan for what to do when logging stops working.",
  },

  "3.3.5": {
    tier: "Shared",
    services: ["Sentinel"],
    microsoftCovers:
      "Sentinel provides cross-service log correlation, investigation workbooks, and hunting queries that combine data from multiple sources in GCC High.",
    customerOwns:
      "Use Sentinel workbooks and hunting queries to correlate events across identity, endpoint, and network logs. Establish regular review cadences and investigate correlated findings.",
    summary:
      "Microsoft built Sentinel to pull together logs from Entra ID, Defender, Intune, and other sources so you can see the full picture. You need to use those correlation tools — workbooks, hunting queries — on a regular schedule and investigate when patterns suggest something is wrong.",
  },

  "3.3.6": {
    tier: "Shared",
    services: ["Sentinel"],
    microsoftCovers:
      "Sentinel provides KQL-based querying, built-in workbooks, and customizable dashboards for audit record filtering, analysis, and report generation in GCC High.",
    customerOwns:
      "Build or customize Sentinel workbooks and reports to support your audit review needs. Generate periodic compliance reports and retain them for assessor review.",
    summary:
      "Microsoft gives you powerful query and reporting tools in Sentinel — workbooks, dashboards, and custom queries. You need to build the specific reports your organization requires, run them on a schedule, and keep copies for your assessor to review during audits.",
  },

  "3.3.7": {
    tier: "Shared",
    services: ["Intune", "Entra ID"],
    microsoftCovers:
      "Microsoft 365 and Azure services in GCC High synchronize to authoritative time sources. Windows Time Service provides NTP synchronization for domain-joined machines.",
    customerOwns:
      "Ensure all endpoints and on-premises servers are configured to sync time from an authoritative NTP source. Verify Intune-managed devices maintain accurate timestamps.",
    summary:
      "Microsoft keeps its cloud services synchronized to accurate time sources automatically. For your on-premises servers and managed devices, you need to make sure they are all pointed at a reliable time source so that timestamps in your audit logs line up correctly.",
  },

  "3.3.8": {
    tier: "Shared",
    services: ["Azure RBAC", "Sentinel"],
    microsoftCovers:
      "Azure RBAC restricts access to Sentinel workspaces and log storage. GCC High infrastructure protects audit data from unauthorized platform-level modification.",
    customerOwns:
      "Restrict Sentinel workspace access to authorized security personnel only. Configure log storage with immutability policies so audit records cannot be altered or deleted.",
    summary:
      "Microsoft protects audit data at the infrastructure level and provides role-based access controls for Sentinel. You need to lock down who can access your Sentinel workspace, limit it to your security team, and set immutability policies so no one can tamper with log records.",
  },

  "3.3.9": {
    tier: "Shared",
    services: ["Azure RBAC", "Sentinel"],
    microsoftCovers:
      "Azure RBAC provides granular role definitions that separate audit log management from other administrative functions in GCC High.",
    customerOwns:
      "Restrict the ability to configure, disable, or modify audit logging to a small set of authorized personnel. Ensure general administrators cannot alter logging settings.",
    summary:
      "Microsoft provides separate roles for managing audit configurations versus other admin tasks. You need to make sure only a small, trusted group can change logging settings — your regular IT admins should not be able to turn off or modify the audit trail.",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 3.4 — CONFIGURATION MANAGEMENT (9 controls)
  // ═══════════════════════════════════════════════════════════════════════════

  "3.4.1": {
    tier: "Inherited",
    services: ["Intune", "Azure Policy", "Defender", "Azure Automation"],
    microsoftCovers:
      "GCC High provides Intune security baselines, Azure Policy built-in initiatives, and Defender for Endpoint security recommendations that serve as starting-point baseline templates for device and cloud resource configurations.",
    customerOwns:
      "Define your organization's approved baseline configurations for all system components, document deviations, and assign owners to review and update baselines at least annually or when systems change.",
    summary:
      "Microsoft gives you ready-made templates and tools in Intune and Azure Policy to lock down device and cloud settings. Your job is to decide which settings are right for your organization, document them as your official baseline, and keep them current as your environment changes.",
  },

  "3.4.2": {
    tier: "Inherited",
    services: ["Intune", "Azure Policy", "Entra ID", "Defender"],
    microsoftCovers:
      "GCC High delivers Intune configuration profiles, Entra ID security defaults, Azure Policy compliance checks, and Defender security recommendations that enforce and monitor security configuration settings across endpoints and cloud resources.",
    customerOwns:
      "Select and apply the most restrictive security configuration settings appropriate for your environment, document exceptions with business justifications, and remediate configuration drift flagged by compliance reports.",
    summary:
      "Microsoft provides the knobs and dials to harden your systems through Intune profiles, Entra defaults, and Defender recommendations. You need to choose the strictest practical settings for your business, apply them, and fix anything that drifts out of compliance.",
  },

  "3.4.3": {
    tier: "Inherited",
    services: ["Defender for Cloud Apps", "Power Automate", "Purview"],
    microsoftCovers:
      "GCC High provides audit logging for configuration changes across Microsoft 365 services, Defender for Cloud Apps policy-change alerts, and Power Automate workflows to route change requests through approval chains.",
    customerOwns:
      "Establish a formal change management process that requires documented requests, security reviews, and management approval before changes are implemented in production systems.",
    summary:
      "Microsoft logs every configuration change and can alert you when something shifts. Your responsibility is to set up an approval process so that no one makes changes to production systems without a documented request and sign-off from the right people.",
  },

  "3.4.4": {
    tier: "Inherited",
    services: ["Defender", "Sentinel", "Azure Policy"],
    microsoftCovers:
      "GCC High offers Defender security posture assessments, Sentinel analytics rules that detect configuration anomalies, and Azure Policy compliance evaluations that flag security impact when resource configurations change.",
    customerOwns:
      "Perform and document a security impact analysis before implementing changes, including evaluating how proposed changes affect existing security controls and CUI protections.",
    summary:
      "Microsoft's tools can detect when a change weakens your security posture and flag the risk. Before you make any change, though, you need to think through and document how it could affect your security controls and your protected data.",
  },

  "3.4.5": {
    tier: "Inherited",
    services: ["Entra ID", "Intune", "Azure Policy"],
    microsoftCovers:
      "GCC High provides Entra ID Conditional Access policies, role-based access control, and Intune compliance policies that enforce logical access restrictions to systems and configuration settings.",
    customerOwns:
      "Define and document which roles and individuals are authorized to access system configurations, physically secure network infrastructure, and maintain an access control policy that maps permissions to job responsibilities.",
    summary:
      "Microsoft gives you Conditional Access and role-based controls in Entra ID to restrict who can touch system settings. You need to decide who should have access, document those decisions in a policy, and make sure physical access to network gear is also locked down.",
  },

  "3.4.6": {
    tier: "Inherited",
    services: ["Intune", "Entra ID", "Defender for Cloud Apps", "Sentinel"],
    microsoftCovers:
      "GCC High provides Intune application control policies, Entra ID app registration controls, Defender for Cloud Apps shadow IT discovery, and Sentinel monitoring to identify unnecessary services and functions running in your environment.",
    customerOwns:
      "Identify essential mission functions and disable or remove all nonessential programs, ports, protocols, and services from organizational systems based on a documented least-functionality policy.",
    summary:
      "Microsoft helps you discover what software and services are running across your environment and gives you tools to block what you do not need. You must decide which functions are essential for your business, then actively disable everything else.",
  },

  "3.4.7": {
    tier: "Inherited",
    services: ["Intune", "Entra ID", "Azure Policy"],
    microsoftCovers:
      "GCC High provides Intune device restriction profiles, Entra ID application consent policies, and Azure Policy deny assignments that can block nonessential programs, functions, ports, protocols, and services.",
    customerOwns:
      "Configure and maintain restriction policies that specifically disable nonessential functions such as USB storage, unnecessary browser extensions, unauthorized cloud storage, and unapproved communication tools.",
    summary:
      "Microsoft provides the enforcement tools in Intune and Entra to block things like USB drives, unapproved apps, and unnecessary services. You need to configure those restrictions based on what your workforce actually needs and keep the block list updated.",
  },

  "3.4.8": {
    tier: "Shared",
    services: ["Intune", "Defender for Cloud Apps", "Azure Firewall"],
    microsoftCovers:
      "GCC High provides Intune application control (AppLocker/WDAC), Defender for Cloud Apps deny-by-default access policies, and Azure Firewall default-deny network rules as enforcement mechanisms for a deny-by-exception approach.",
    customerOwns:
      "Define your deny-all-permit-by-exception policy, build and maintain the approved software and network allowlists, configure Intune application control and Azure Firewall rules to enforce them, and review the allowlists regularly.",
    summary:
      "Microsoft provides the enforcement tools — Intune application control, Azure Firewall default-deny rules, and Defender for Cloud Apps policies — all available in GCC High. You define what goes on the approved list, configure the policies in Intune to block everything else, and review that list regularly to keep it current.",
  },

  "3.4.9": {
    tier: "Inherited",
    services: ["Intune", "Defender", "Azure Firewall"],
    microsoftCovers:
      "GCC High provides Intune application management policies, Defender for Endpoint application control, and Azure Firewall rules that monitor and restrict software installation and execution on managed devices.",
    customerOwns:
      "Establish a software installation policy, configure application allowlists and blocklists in Intune, and monitor Defender alerts for unauthorized software installations across all endpoints.",
    summary:
      "Microsoft gives you Intune and Defender to control and monitor what software gets installed on company devices. You need to set a clear policy about what users can and cannot install, configure the tools to enforce it, and respond when someone tries to install something unapproved.",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 3.5 — IDENTIFICATION & AUTHENTICATION (11 controls)
  // ═══════════════════════════════════════════════════════════════════════════

  "3.5.1": {
    tier: "Shared",
    services: ["Entra ID", "Intune", "Azure Policy"],
    microsoftCovers:
      "GCC High provides Entra ID as the identity provider with unique user identifiers, managed identities for service accounts, and Intune device identity enrollment that uniquely identifies every user, device, and process.",
    customerOwns:
      "Maintain an accurate user and service account inventory, promptly provision and deprovision accounts aligned with HR actions, and ensure every process acting on behalf of a user is tied to an identifiable account.",
    summary:
      "Microsoft's Entra ID assigns every user, device, and service account a unique identity in your tenant. Your job is to keep that identity list accurate — add people when they join, remove them when they leave, and make sure automated processes are tied to a responsible person.",
  },

  "3.5.2": {
    tier: "Shared",
    services: ["Entra ID", "Conditional Access", "Intune"],
    microsoftCovers:
      "GCC High provides Entra ID authentication services, Conditional Access policy engine, certificate-based authentication, and Intune device compliance checks that verify the identity of users, devices, and processes before granting access.",
    customerOwns:
      "Configure Conditional Access policies appropriate for your risk profile, enforce device compliance requirements, and define authentication strength requirements for different access scenarios including privileged operations.",
    summary:
      "Microsoft handles the actual identity verification through Entra ID and lets you set conditions for access through Conditional Access. You decide the rules — which users need stronger proof of identity, which devices must be compliant, and what conditions trigger extra checks.",
  },

  "3.5.3": {
    tier: "Shared",
    services: ["Entra ID", "Conditional Access"],
    microsoftCovers:
      "GCC High includes Entra ID MFA capabilities at no additional cost with G5 licensing, supporting FIDO2 security keys, Microsoft Authenticator push notifications, phone-based verification, and certificate-based authentication methods.",
    customerOwns:
      "Enable and enforce MFA for all users via Conditional Access policies, select approved authentication methods that meet CMMC requirements, register users for MFA, and ensure MFA coverage includes all access paths including VPN and remote access.",
    summary:
      "Microsoft includes MFA with your G5 license and supports multiple strong methods like the Authenticator app and security keys. You must turn it on for everyone through Conditional Access, pick which methods to allow, and make sure there are no gaps where someone can sign in without a second factor.",
  },

  "3.5.4": {
    tier: "Shared",
    services: ["Entra ID", "Conditional Access", "Azure Key Vault"],
    microsoftCovers:
      "GCC High Entra ID authentication protocols including OAuth 2.0, OpenID Connect, and SAML include built-in replay-resistant mechanisms such as nonce values, token binding, and time-limited tokens that prevent authentication replay attacks.",
    customerOwns:
      "Ensure all authentication flows use modern protocols supported by Entra ID, eliminate legacy authentication methods that lack replay resistance, and configure Conditional Access to block legacy authentication protocols.",
    summary:
      "Microsoft's Entra ID uses modern sign-in protocols that automatically prevent someone from capturing and reusing your login session. You need to make sure legacy sign-in methods are blocked through Conditional Access so every authentication goes through these protected channels.",
  },

  "3.5.5": {
    tier: "Shared",
    services: ["Entra ID"],
    microsoftCovers:
      "GCC High Entra ID enforces globally unique identifiers for all user, group, and service principal objects and prevents reassignment of deleted object identifiers within the tenant for the configured soft-delete retention period.",
    customerOwns:
      "Establish a naming convention and account lifecycle policy that prevents identifier reuse, ensure deleted accounts remain in soft-delete state for an appropriate period, and document your identifier management procedures.",
    summary:
      "Microsoft automatically assigns unique IDs in Entra and keeps deleted accounts in a recovery state so their IDs are not recycled. You should have a naming convention and a policy that defines how long deleted accounts are retained before permanent removal to prevent any confusion about who had access.",
  },

  "3.5.6": {
    tier: "Shared",
    services: ["Entra ID", "Conditional Access"],
    microsoftCovers:
      "GCC High Entra ID provides configurable account inactivity policies, access reviews for periodic recertification, and Conditional Access sign-in risk policies that can detect and respond to dormant accounts.",
    customerOwns:
      "Configure and enforce automatic account disablement after the DoD-defined inactivity period of 90 days or less, run regular access reviews, and establish a process to investigate and disable stale accounts promptly.",
    summary:
      "Microsoft gives you the settings in Entra ID to automatically disable accounts that have not been used for a set period. You need to configure that threshold to 90 days or less per DoD requirements, run regular access reviews, and have a process for cleaning up stale accounts.",
  },

  "3.5.7": {
    tier: "Shared",
    services: ["Entra ID"],
    microsoftCovers:
      "GCC High Entra ID supports configurable password policies including minimum length and complexity requirements, plus Entra Password Protection which blocks known-weak passwords and custom banned password lists.",
    customerOwns:
      "Configure password policies in Entra ID to meet or exceed DoD-defined complexity requirements, enable Entra Password Protection with a custom banned password list relevant to your organization, and communicate password requirements to all users.",
    summary:
      "Microsoft provides password policy settings and a smart banned-password list in Entra that blocks commonly compromised passwords. You must configure the minimum length and complexity to meet DoD standards, add organization-specific terms to the banned list, and make sure your users understand the requirements.",
  },

  "3.5.8": {
    tier: "Shared",
    services: ["Entra ID"],
    microsoftCovers:
      "GCC High Entra ID maintains password history and can enforce password reuse restrictions, preventing users from cycling back to previously used passwords within a configurable history window.",
    customerOwns:
      "Configure Entra ID password policies to prohibit reuse of at least the last 24 passwords per DoD requirements, and communicate the reuse policy to users so they understand they cannot recycle old passwords.",
    summary:
      "Microsoft tracks password history in Entra ID so users cannot reuse old passwords. You need to configure the history limit to meet DoD requirements and let your team know they will need to create genuinely new passwords each time they are required to change them.",
  },

  "3.5.9": {
    tier: "Shared",
    services: ["Entra ID"],
    microsoftCovers:
      "GCC High Entra ID supports Temporary Access Pass issuance with configurable lifetime and one-time-use settings, providing a secure mechanism for temporary credential scenarios such as new-hire onboarding and MFA recovery.",
    customerOwns:
      "Establish a policy governing when temporary passwords or Temporary Access Passes may be issued, enforce immediate change on first use, set short expiration windows, and train help desk staff on secure issuance procedures.",
    summary:
      "Microsoft offers Temporary Access Pass in Entra ID, which gives new hires or locked-out users a short-lived code to get in. You need a policy for when your help desk can issue these, make sure they expire quickly, and require users to set up their real credentials immediately after first login.",
  },

  "3.5.10": {
    tier: "Shared",
    services: ["Entra ID", "Azure Key Vault", "Intune"],
    microsoftCovers:
      "GCC High Entra ID stores password hashes using industry-standard cryptographic algorithms, enforces TLS 1.2+ for all authentication traffic in transit, and Azure Key Vault provides FIPS 140-2 validated HSM-backed secret storage.",
    customerOwns:
      "Ensure all applications and services in your environment authenticate through Entra ID rather than storing credentials locally, verify that no systems transmit passwords in cleartext, and use Azure Key Vault for any secrets that must be stored outside Entra.",
    summary:
      "Microsoft encrypts all passwords at rest and in transit across Entra ID and Azure using strong, government-validated cryptography. Your part is making sure none of your own applications or processes store passwords in plain text or send them over unencrypted connections. Route everything through Entra ID when possible.",
  },

  "3.5.11": {
    tier: "Inherited",
    services: ["Entra ID"],
    microsoftCovers:
      "GCC High Entra ID login interfaces mask password input fields by default across all Microsoft sign-in experiences, displaying dots or asterisks instead of plaintext characters during authentication.",
    customerOwns:
      "Verify that any custom or third-party applications integrated with your environment also obscure password entry fields and do not display authentication credentials in plaintext on screen.",
    summary:
      "Microsoft already hides passwords behind dots on all its sign-in screens so users never see their password displayed in the clear. If you use any custom or third-party apps, just make sure those also mask the password field during login.",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 3.6 — INCIDENT RESPONSE (3 controls)
  // ═══════════════════════════════════════════════════════════════════════════

  "3.6.1": {
    tier: "Inherited",
    services: ["Sentinel", "Defender for Cloud Apps", "Defender"],
    microsoftCovers:
      "GCC High provides Sentinel SIEM with built-in detection rules, automated playbooks, and incident queues, plus Defender XDR for cross-product incident correlation and automated investigation and response capabilities.",
    customerOwns:
      "Develop and maintain a written incident response plan that defines roles, escalation procedures, communication protocols, and recovery steps. Train your team on the plan and assign specific individuals to incident response roles.",
    summary:
      "Microsoft gives you a full detection and response platform in Sentinel and Defender that spots threats and can respond automatically to some of them. But you need a written plan that says who does what when an incident happens, how you escalate, and who you notify. The tools are only as good as the people and process behind them.",
  },

  "3.6.2": {
    tier: "Inherited",
    services: ["Sentinel", "Entra ID", "Defender"],
    microsoftCovers:
      "GCC High Sentinel provides incident tracking dashboards, case management, evidence collection, and automated reporting. Entra ID audit and sign-in logs feed into Sentinel for comprehensive incident timelines.",
    customerOwns:
      "Document all incidents from detection through resolution using your case management workflow, report security incidents to your DIBCAC and contracting officer as required, and maintain incident records for the retention period defined by your contract.",
    summary:
      "Microsoft's Sentinel tracks incidents end to end with timelines and evidence. Your responsibility is to make sure every incident gets properly documented, reported to the right people including your contracting officer when CUI is involved, and retained in your records for as long as required.",
  },

  "3.6.3": {
    tier: "Inherited",
    services: ["Sentinel", "Defender"],
    microsoftCovers:
      "GCC High Sentinel provides attack simulation capabilities, and Defender XDR supports automated investigation playbooks that can be used as a foundation for tabletop exercises and technical incident response drills.",
    customerOwns:
      "Plan and conduct regular incident response tests such as tabletop exercises or simulated incidents at least annually, document lessons learned, and update your incident response plan based on test findings.",
    summary:
      "Microsoft provides simulation and playbook tools in Sentinel and Defender that you can use for practice drills. You must actually schedule and run these exercises at least once a year, document what went well and what did not, and update your incident response plan based on what you learn.",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 3.7 — MAINTENANCE (6 controls)
  // ═══════════════════════════════════════════════════════════════════════════

  "3.7.1": {
    tier: "Inherited",
    services: ["Intune", "Defender"],
    microsoftCovers:
      "Microsoft maintains all GCC High cloud infrastructure — patching Azure VMs, updating M365 services, and managing hypervisor and host-OS maintenance on a published schedule with zero customer downtime.",
    customerOwns:
      "You must maintain any on-premises or hybrid systems yourself, including scheduling patches through Intune, applying firmware updates, and documenting a maintenance policy with defined roles and frequencies.",
    summary:
      "Microsoft keeps its cloud servers and M365 services patched and updated automatically — you never touch that infrastructure. Your job is to make sure your own laptops, servers, and network gear stay up to date too, and that you have a written maintenance schedule your team follows.",
  },

  "3.7.2": {
    tier: "Inherited",
    services: ["Entra ID", "Intune"],
    microsoftCovers:
      "Azure RBAC and Entra Privileged Identity Management (PIM) enforce just-in-time, least-privilege access for all maintenance performed on GCC High infrastructure, with full audit logging.",
    customerOwns:
      "You must define who is authorized to perform maintenance on your systems, enforce approval workflows for elevated access, and ensure maintenance tools and accounts are inventoried and reviewed regularly.",
    summary:
      "Microsoft locks down who can perform maintenance on its cloud systems using strict role-based controls and just-in-time access. You need to do the same for your own environment — know who has maintenance access, require approvals for elevated privileges, and review that list periodically.",
  },

  "3.7.3": {
    tier: "Inherited",
    services: ["Entra ID", "Intune"],
    microsoftCovers:
      "Microsoft sanitizes and cryptographically wipes all cloud hardware before it leaves Azure datacenters, following NIST 800-88 media sanitization guidelines with documented chain-of-custody procedures.",
    customerOwns:
      "You must establish procedures for sanitizing company devices (laptops, drives) before sending them out for repair, including verifying encryption is active, revoking credentials, and wiping CUI from any equipment leaving your control.",
    summary:
      "Microsoft wipes its own hardware clean before it ever leaves a datacenter — that part is handled. If you need to send a company laptop or drive out for repair, you must remove all CUI first, make sure the drive is encrypted, and revoke any saved credentials before it leaves your office.",
  },

  "3.7.4": {
    tier: "Inherited",
    services: ["Defender"],
    microsoftCovers:
      "Microsoft scans all maintenance media and tools used on GCC High infrastructure for malicious code before use, leveraging isolated bastion hosts and air-gapped management networks.",
    customerOwns:
      "You must scan any USB drives, diagnostic tools, or external media for malware before connecting them to systems that handle CUI, and document a policy prohibiting unscanned media on your network.",
    summary:
      "Microsoft checks every tool and media device for malware before using it on cloud infrastructure. You need to do the same at your office — scan any USB drive or diagnostic tool before plugging it into a company system, and have a policy that says this is required.",
  },

  "3.7.5": {
    tier: "Inherited",
    services: ["Entra ID"],
    microsoftCovers:
      "All remote maintenance sessions to GCC High infrastructure require multifactor authentication through Microsoft's internal identity systems, with session recording and audit trails.",
    customerOwns:
      "You must enforce MFA for anyone performing remote maintenance on your systems — IT admins, managed service providers, or vendors — using Entra ID Conditional Access policies that require MFA for privileged sessions.",
    summary:
      "Microsoft already requires MFA for anyone maintaining cloud infrastructure remotely. You need to enforce the same rule for your own environment — any IT admin or vendor doing remote work on your systems must authenticate with MFA, no exceptions.",
  },

  "3.7.6": {
    tier: "Inherited",
    services: ["Defender"],
    microsoftCovers:
      "Microsoft monitors and supervises all nonlocal maintenance sessions on GCC High infrastructure through recorded sessions, real-time oversight, and automated anomaly detection.",
    customerOwns:
      "You must supervise remote maintenance by vendors or IT staff on your systems — use screen-sharing observation, session recording, or Defender for Endpoint telemetry to maintain oversight of what is being done.",
    summary:
      "Microsoft watches every remote maintenance session on its cloud systems in real time. For your own systems, you need to supervise remote work done by IT staff or vendors — watch the session, record it, or at minimum review logs of what they did afterward.",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 3.8 — MEDIA PROTECTION (9 controls)
  // ═══════════════════════════════════════════════════════════════════════════

  "3.8.1": {
    tier: "Inherited",
    services: ["Purview", "Intune"],
    microsoftCovers:
      "Microsoft protects all CUI stored in GCC High services using encryption at rest (AES-256) and in transit (TLS 1.2+), with Azure Key Vault managing encryption keys in FIPS 140-2 validated modules.",
    customerOwns:
      "You must identify which physical and digital media contain CUI, restrict who can access that media, store physical media in locked containers, and document your media protection policy.",
    summary:
      "Microsoft encrypts your data automatically in the cloud — at rest and in transit. Your responsibility is the physical side: printed CUI goes in locked cabinets, USB drives with CUI are stored securely, and you have a written policy that says who can access media containing sensitive information.",
  },

  "3.8.2": {
    tier: "Inherited",
    services: ["Purview", "Intune"],
    microsoftCovers:
      "Azure Key Vault and Intune device compliance policies restrict access to encrypted CUI in GCC High, ensuring only managed, compliant devices and authorized users can decrypt and view protected content.",
    customerOwns:
      "You must configure Purview sensitivity labels to restrict CUI access, enforce Intune compliance policies on devices that access CUI media, and limit physical media distribution to authorized personnel only.",
    summary:
      "Microsoft provides the tools — sensitivity labels, device compliance, encryption — to restrict who sees CUI on digital media. You need to turn those on and also control the physical side: only hand CUI documents or drives to people who actually need them for their job.",
  },

  "3.8.3": {
    tier: "Inherited",
    services: ["Intune"],
    microsoftCovers:
      "Microsoft sanitizes all cloud storage media using NIST 800-88 compliant procedures before reuse or disposal, with documented destruction certificates for decommissioned GCC High hardware.",
    customerOwns:
      "You must establish media sanitization procedures for company-owned devices and storage — use certified wiping tools or physical destruction for hard drives, shred paper CUI, and maintain disposal logs.",
    summary:
      "Microsoft destroys or wipes its own cloud hardware when it's retired — that's covered. Your job is your own media: shred printed CUI, use certified disk-wiping tools before recycling old laptops or drives, and keep a log showing what was destroyed and when.",
  },

  "3.8.4": {
    tier: "Inherited",
    services: ["Purview"],
    microsoftCovers:
      "Purview sensitivity labels in GCC High can automatically apply CUI markings to documents and emails, with label policies enforced tenant-wide.",
    customerOwns:
      "You must configure and deploy Purview sensitivity labels that mark CUI appropriately, train users to apply labels consistently, and establish marking procedures for physical media.",
    summary:
      "Microsoft gives you Purview sensitivity labels that can automatically stamp documents and emails with CUI markings. You need to set those labels up, train your team to use them, and also have a process for marking physical items like printed documents or USB drives.",
  },

  "3.8.5": {
    tier: "Inherited",
    services: ["Intune", "Defender"],
    microsoftCovers:
      "Intune device management and Defender for Endpoint provide device control policies in GCC High that can restrict media access to compliant, managed endpoints with full audit logging.",
    customerOwns:
      "You must configure Intune and Defender device control policies to limit which devices can access CUI media, restrict unauthorized peripherals, and maintain access control records for physical media storage areas.",
    summary:
      "Microsoft gives you device management tools that control which computers and peripherals can access your data. You need to configure those policies — block unauthorized devices, restrict USB access where appropriate — and also control who can physically get to stored media in your office.",
  },

  "3.8.6": {
    tier: "Inherited",
    services: ["Intune", "Purview"],
    microsoftCovers:
      "GCC High provides BitLocker management through Intune for full-disk encryption and Azure Key Vault for key management, both using FIPS 140-2 validated cryptographic modules.",
    customerOwns:
      "You must enforce BitLocker encryption on all endpoints via Intune compliance policies, configure Purview for email and document encryption, and verify encryption is active on any portable media containing CUI.",
    summary:
      "Microsoft provides BitLocker for disk encryption and Purview for document encryption, all managed through Intune. You need to make sure those are turned on — every laptop must have BitLocker enabled, and any USB drive or portable media carrying CUI must be encrypted too.",
  },

  "3.8.7": {
    tier: "Inherited",
    services: ["Intune", "Defender"],
    microsoftCovers:
      "Defender for Endpoint and Intune provide device control profiles in GCC High that can block, allow, or audit removable media usage across managed endpoints with granular policy enforcement.",
    customerOwns:
      "You must configure device control policies to restrict or block removable media, define exceptions with business justification, and enforce encryption requirements on any allowed removable media.",
    summary:
      "Microsoft gives you the ability to block or restrict USB drives and other removable media across your fleet using Intune and Defender. You need to decide your policy — block them entirely or allow them with encryption — configure the rules, and document the exceptions.",
  },

  "3.8.8": {
    tier: "Inherited",
    services: ["Intune", "Defender"],
    microsoftCovers:
      "Intune and Defender for Endpoint enforce device control policies in GCC High that can prohibit portable storage devices without an identifiable owner, blocking unregistered media at the endpoint level.",
    customerOwns:
      "You must require all portable storage devices to be registered and assigned to a specific owner, configure Intune policies to block unrecognized devices, and maintain an inventory of approved removable media.",
    summary:
      "Microsoft's tools can block any USB drive or portable storage device that isn't on your approved list. You need to maintain that list — every USB drive should have an assigned owner — and configure Intune to reject anything that's not registered.",
  },

  "3.8.9": {
    tier: "Shared",
    services: ["Entra ID", "Purview"],
    microsoftCovers:
      "GCC High encrypts all backup data at rest using AES-256 and enforces RBAC through Entra ID, ensuring backup repositories are access-controlled with the same rigor as production data.",
    customerOwns:
      "You must verify that backup procedures maintain CUI confidentiality, restrict backup access to authorized administrators via Entra ID roles, test backup restoration procedures, and ensure any off-site backup media is encrypted.",
    summary:
      "Microsoft encrypts your cloud backups and restricts access through role-based controls. Your part is making sure the right people — and only the right people — can access those backups, testing that restores actually work, and securing any backup copies you keep outside the cloud.",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 3.9 — PERSONNEL SECURITY (2 controls)
  // ═══════════════════════════════════════════════════════════════════════════

  "3.9.1": {
    tier: "Shared",
    services: [],
    microsoftCovers:
      "Microsoft screens all personnel with access to GCC High infrastructure through government-level background checks, but provides no tooling for screening your employees.",
    customerOwns:
      "You must implement a personnel screening process — background checks, reference verification, and suitability determinations — before granting any individual access to CUI systems.",
    summary:
      "Microsoft screens its own employees who run the cloud, but screening your people is entirely on you. Before anyone gets access to CUI, you need background checks and a documented process for deciding who is trustworthy enough. This is an HR function — no technology shortcut here.",
  },

  "3.9.2": {
    tier: "Shared",
    services: ["Entra ID"],
    microsoftCovers:
      "Entra ID and Azure RBAC provide the mechanism to immediately disable accounts, revoke access, and reassign permissions when personnel changes occur in your GCC High tenant.",
    customerOwns:
      "You must establish procedures to disable accounts and recover CUI when employees transfer or depart — including revoking access within the same day, retrieving company devices, and reassigning data ownership.",
    summary:
      "Microsoft gives you the tools to disable accounts and revoke access instantly through Entra ID. Your job is to use them — have a documented offboarding process so that when someone leaves or changes roles, their access is cut the same day and any CUI they held is recovered or reassigned.",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 3.10 — PHYSICAL PROTECTION (6 controls)
  // ═══════════════════════════════════════════════════════════════════════════

  "3.10.1": {
    tier: "Inherited",
    services: ["Entra ID", "Intune"],
    microsoftCovers:
      "Azure datacenters enforce multi-layered physical access controls — biometric scanners, mantraps, 24/7 security staff, and video surveillance — meeting FedRAMP High physical security requirements.",
    customerOwns:
      "You must control physical access to your own offices where CUI is accessed or stored — badge readers, locked server rooms, visitor sign-in logs — and use Conditional Access to restrict CUI access to trusted locations.",
    summary:
      "Microsoft's datacenters are locked down with biometrics, guards, and cameras — that's fully handled. Your responsibility is your own office: lock the doors, control who gets in, use badge access for sensitive areas, and consider Conditional Access policies that limit CUI access to your office network.",
  },

  "3.10.2": {
    tier: "Inherited",
    services: ["Intune"],
    microsoftCovers:
      "Azure datacenters are continuously monitored with CCTV, intrusion detection, environmental controls, and 24/7 security operations centers, all audited under FedRAMP High.",
    customerOwns:
      "You must monitor your own facility — security cameras in sensitive areas, intrusion alarms, environmental protections for any on-premises equipment, and regular walkthroughs to verify controls are working.",
    summary:
      "Microsoft monitors its datacenters around the clock with cameras, alarms, and security teams. For your office, you need your own physical security — cameras where CUI is stored, alarms on doors, and someone checking that those controls are actually working on a regular basis.",
  },

  "3.10.3": {
    tier: "Inherited",
    services: [],
    microsoftCovers:
      "Azure datacenters require all visitors to be pre-approved, escorted at all times, and logged — no unescorted visitor access is permitted within GCC High facility boundaries.",
    customerOwns:
      "You must establish a visitor management process for your own facility — require sign-in, issue visitor badges, escort visitors in areas where CUI is accessible, and maintain visitor logs.",
    summary:
      "Microsoft escorts every visitor in its datacenters — no exceptions. You need the same discipline at your office: visitors sign in, get a badge, and are escorted through areas where CUI could be seen or accessed. Keep a log of who visited and when.",
  },

  "3.10.4": {
    tier: "Inherited",
    services: ["Intune"],
    microsoftCovers:
      "Azure datacenters maintain comprehensive physical access audit logs — every badge swipe, door entry, and visitor check-in is recorded and retained in compliance with FedRAMP High requirements.",
    customerOwns:
      "You must maintain audit logs of physical access to your own facility — badge reader logs, visitor sign-in sheets, and security camera footage — and retain them according to your records retention policy.",
    summary:
      "Microsoft keeps detailed logs of every person who enters its datacenters. You need audit logs for your own office too — badge reader history, visitor sign-in sheets, and camera footage. Keep these records so you can prove who had physical access and when.",
  },

  "3.10.5": {
    tier: "Inherited",
    services: [],
    microsoftCovers:
      "Azure datacenters manage all physical access devices — key cards, biometric readers, lock systems — with regular inventory, revocation procedures, and replacement protocols under FedRAMP High controls.",
    customerOwns:
      "You must manage your physical access devices — keys, badges, access cards, PINs — including inventorying them, revoking lost or stolen credentials promptly, and changing combinations when personnel depart.",
    summary:
      "Microsoft manages all the keys and badges for its datacenters. At your office, you need to track who has keys, badges, and access codes. When someone leaves, collect their badge and change shared codes. Keep an inventory so you always know who can physically get in.",
  },

  "3.10.6": {
    tier: "Inherited",
    services: ["Entra ID", "Intune", "Defender"],
    microsoftCovers:
      "GCC High provides Conditional Access, Intune compliance policies, and Defender for Endpoint to enforce security posture on devices regardless of location, including MFA and device health checks.",
    customerOwns:
      "You must define safeguarding measures for alternate work sites — enforce full-disk encryption, require VPN or Conditional Access, mandate MFA, and publish a remote work security policy employees must acknowledge.",
    summary:
      "Microsoft gives you tools to secure devices no matter where they are — Conditional Access, Intune compliance, MFA. But you need a remote work policy that says what's required: encrypted laptops, MFA always on, no working from public Wi-Fi without a VPN, and no CUI on personal devices.",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 3.11 — RISK ASSESSMENT (3 controls)
  // ═══════════════════════════════════════════════════════════════════════════

  "3.11.1": {
    tier: "Inherited",
    services: ["Defender", "Sentinel"],
    microsoftCovers:
      "Microsoft Defender and Sentinel in GCC High provide continuous threat intelligence, risk scoring via Secure Score, and automated risk assessments of your cloud environment's security posture.",
    customerOwns:
      "You must perform periodic organizational risk assessments that go beyond technology — evaluate business processes, third-party risks, and physical threats — and document findings in a risk register.",
    summary:
      "Microsoft gives you Secure Score and Defender dashboards that continuously assess your cloud security posture. But a real risk assessment is bigger than technology — you need to look at your whole business, identify what could go wrong, and write it down in a risk register with plans to address each item.",
  },

  "3.11.2": {
    tier: "Shared",
    services: ["Defender", "Sentinel"],
    microsoftCovers:
      "Defender for Endpoint and Defender Vulnerability Management in GCC High continuously scan managed endpoints and cloud workloads for known vulnerabilities with severity ratings and remediation guidance.",
    customerOwns:
      "You must ensure vulnerability scanning covers all systems in scope, review scan results regularly, prioritize findings by severity, and track remediation to closure with documented timelines.",
    summary:
      "Microsoft's Defender automatically scans your managed devices for vulnerabilities and tells you what's wrong. Your job is to make sure everything is being scanned — not just laptops but servers, network gear, and applications — and that you're reviewing the results and fixing what's found.",
  },

  "3.11.3": {
    tier: "Shared",
    services: ["Defender", "Intune"],
    microsoftCovers:
      "Defender Vulnerability Management and Intune in GCC High provide automated patch deployment, remediation recommendations, and tracking dashboards to help close identified vulnerabilities.",
    customerOwns:
      "You must act on vulnerability findings — approve and deploy patches through Intune, remediate configuration weaknesses, track remediation progress against defined timelines, and document risk for anything you cannot immediately fix.",
    summary:
      "Microsoft tells you what's vulnerable and can push patches automatically through Intune. But you still have to approve those patches, set deployment timelines, and fix configuration issues that patches don't cover. If something can't be fixed right away, document why and what you're doing about it.",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 3.12 — SECURITY ASSESSMENT (4 controls)
  // ═══════════════════════════════════════════════════════════════════════════

  "3.12.1": {
    tier: "Inherited",
    services: ["Defender", "Sentinel", "Intune"],
    microsoftCovers:
      "Secure Score, Defender, and Sentinel in GCC High continuously evaluate your tenant's security posture against best practices, providing scored recommendations and compliance benchmarks.",
    customerOwns:
      "You must periodically assess whether your security controls are implemented correctly and operating effectively — conduct formal reviews, document results, and address gaps with corrective actions.",
    summary:
      "Microsoft gives you a continuous security scorecard through Secure Score, Defender, and Sentinel. But having the tools isn't enough — you need to formally review your security controls on a regular schedule, document what's working and what isn't, and take action to close any gaps.",
  },

  "3.12.2": {
    tier: "Inherited",
    services: ["Defender", "Sentinel"],
    microsoftCovers:
      "Defender and Sentinel in GCC High provide prioritized remediation recommendations and can integrate with ticketing systems to track remediation actions from discovery through closure.",
    customerOwns:
      "You must develop Plan of Action and Milestones (POA&M) documents for security weaknesses, assign responsible parties, set remediation deadlines, track progress, and update plans as conditions change.",
    summary:
      "Microsoft identifies security issues and suggests fixes through Defender and Sentinel. Your job is to turn those into a formal action plan — a POA&M document that lists every weakness, who's responsible for fixing it, when it will be fixed, and what progress has been made.",
  },

  "3.12.3": {
    tier: "Inherited",
    services: ["Defender", "Sentinel"],
    microsoftCovers:
      "Sentinel and Defender in GCC High provide continuous security monitoring with real-time alerting, automated response playbooks, and dashboard visibility into your tenant's security posture.",
    customerOwns:
      "You must establish ongoing monitoring procedures — define what gets monitored, set alert thresholds, assign staff to review alerts, and ensure security events are investigated and resolved timely.",
    summary:
      "Microsoft provides real-time monitoring through Sentinel and Defender with alerts and dashboards. But someone on your team needs to actually watch those dashboards, investigate alerts when they fire, and have a documented process for who responds to what.",
  },

  "3.12.4": {
    tier: "Inherited",
    services: ["Defender", "Sentinel", "Intune"],
    microsoftCovers:
      "Azure Monitor, Sentinel, Defender, and Intune in GCC High provide real-time system configuration data, security baselines, and compliance reporting that feed into system security documentation.",
    customerOwns:
      "You must develop and maintain a System Security Plan (SSP) that describes your system boundary, security controls, how they're implemented, and the current authorization status — and update it whenever the environment changes.",
    summary:
      "Microsoft gives you the data you need — configuration reports, compliance dashboards, security baselines — to describe your environment accurately. Your job is to write and maintain a System Security Plan that documents what your system looks like, how it's protected, and keep it current as things change.",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 3.13 — SYSTEM & COMMUNICATIONS PROTECTION (16 controls)
  // ═══════════════════════════════════════════════════════════════════════════

  "3.13.1": {
    tier: "Inherited",
    services: ["Azure Networking", "Sentinel"],
    microsoftCovers:
      "GCC High provides boundary monitoring at the platform level through Azure Firewall, network security groups, and built-in DDoS protection across all tenant traffic.",
    customerOwns:
      "Review Microsoft-provided boundary monitoring logs in Sentinel and escalate anomalies through your incident response process.",
    summary:
      "Microsoft monitors all network boundaries in GCC High at the infrastructure level — this is one of the few controls they fully own. Your team should still review Sentinel dashboards periodically to stay aware of boundary events, but the heavy lifting is handled by the platform.",
  },

  "3.13.2": {
    tier: "Shared",
    services: ["Azure Networking", "Entra ID", "Defender"],
    microsoftCovers:
      "GCC High provides security architecture building blocks including network segmentation, zero-trust identity via Entra ID, and Defender security baselines.",
    customerOwns:
      "Design and document your security architecture, including network topology decisions, trust boundaries, and how CUI flows through your environment.",
    summary:
      "Microsoft provides the architectural building blocks in GCC High — network segmentation, identity management, and security baselines. Your job is to design how those pieces fit together for your business and document your architecture so an assessor can see the big picture.",
  },

  "3.13.3": {
    tier: "Shared",
    services: ["Entra ID", "Intune"],
    microsoftCovers:
      "GCC High provides Privileged Identity Management (PIM), Conditional Access, and role-based access control to separate administrative functions from standard user access.",
    customerOwns:
      "Configure PIM roles, enforce Conditional Access policies that restrict admin portals, and ensure day-to-day users cannot access management interfaces.",
    summary:
      "Microsoft provides Entra ID PIM and Conditional Access in GCC High to keep admin functions separate from regular user access. You need to configure those roles and policies so your admins use elevated access only when needed and normal users never see management consoles.",
  },

  "3.13.4": {
    tier: "Shared",
    services: ["Azure Networking", "Intune", "Defender", "Purview"],
    microsoftCovers:
      "GCC High provides network security groups, web application firewalls, Defender for Office 365, and Purview data loss prevention to control information flow.",
    customerOwns:
      "Define and enforce DLP policies in Purview, configure NSG and WAF rules, and set Intune device compliance policies to prevent unauthorized data transfers.",
    summary:
      "Microsoft provides DLP tools in Purview, network firewalls, and Defender in GCC High to help block unauthorized data movement. You must set up the DLP rules, configure firewall policies, and define what counts as unauthorized transfer for your CUI.",
  },

  "3.13.5": {
    tier: "Inherited",
    services: ["Azure Networking"],
    microsoftCovers:
      "GCC High infrastructure implements network segmentation with publicly accessible components isolated in separate subnetworks using Azure virtual networks, load balancers, and NSGs.",
    customerOwns:
      "Verify your Azure network topology places any public-facing resources in isolated subnets and review Microsoft's shared responsibility documentation for your deployment.",
    summary:
      "Microsoft handles network segmentation for public-facing components at the GCC High infrastructure level — another control they largely own. If you deploy any public-facing Azure resources, confirm they sit in properly isolated subnets, but the platform architecture does the heavy lifting.",
  },

  "3.13.6": {
    tier: "Shared",
    services: ["Azure Networking", "Intune", "Defender"],
    microsoftCovers:
      "GCC High provides Azure Firewall with default-deny capability, NSGs, and Defender for IoT to enforce network traffic restrictions at multiple layers.",
    customerOwns:
      "Configure Azure Firewall and NSG rules to default-deny all inbound and outbound traffic, then create explicit allow rules only for approved traffic flows.",
    summary:
      "Microsoft provides Azure Firewall and NSGs in GCC High that support deny-by-default network rules. You need to actually configure those firewalls to block everything by default and only allow the specific traffic your business requires — no open-by-default shortcuts.",
  },

  "3.13.7": {
    tier: "Shared",
    services: ["Azure Networking", "Entra ID", "Intune"],
    microsoftCovers:
      "GCC High provides Azure Firewall forced tunneling, Entra ID Conditional Access, and Azure Virtual Desktop to route all remote traffic through controlled gateways.",
    customerOwns:
      "Configure VPN and Conditional Access policies to prevent split tunneling, ensuring all remote user traffic routes through your organization's security stack.",
    summary:
      "Microsoft provides forced tunneling and Conditional Access in GCC High so remote workers' traffic goes through your security controls. You must configure VPN policies and Conditional Access rules to block split tunneling — meaning no direct internet access that bypasses your firewalls.",
  },

  "3.13.8": {
    tier: "Shared",
    services: ["Purview", "Intune", "Azure Networking"],
    microsoftCovers:
      "GCC High provides Office Message Encryption, TLS for data in transit, Azure Key Vault for key management, and ExpressRoute for private connectivity.",
    customerOwns:
      "Enable and enforce encryption policies for email and file transfers containing CUI, configure Intune to require encrypted connections, and define which data requires encryption in transit.",
    summary:
      "Microsoft provides encryption tools in GCC High — message encryption, TLS connections, and Key Vault. You need to turn on encryption policies for emails and files that contain CUI, configure devices to require secure connections, and make sure nothing sensitive travels unencrypted.",
  },

  "3.13.9": {
    tier: "Shared",
    services: ["Entra ID", "Azure Networking", "Intune"],
    microsoftCovers:
      "GCC High provides session timeout capabilities in Entra ID, Azure VPN Gateway idle disconnect, and Intune device compliance session controls.",
    customerOwns:
      "Configure session timeout policies in Entra ID Conditional Access, set VPN idle disconnect timers, and define Intune compliance policies for session termination.",
    summary:
      "Microsoft provides session timeout settings in Entra ID and VPN Gateway in GCC High. You need to configure how long idle sessions last before they disconnect — set timeout values in Conditional Access and VPN policies so abandoned connections don't stay open indefinitely.",
  },

  "3.13.10": {
    tier: "Shared",
    services: ["Azure Networking", "Purview"],
    microsoftCovers:
      "GCC High provides Azure Key Vault for centralized cryptographic key lifecycle management including generation, storage, rotation, and revocation with FIPS 140-2 Level 2 validated HSMs.",
    customerOwns:
      "Establish key management procedures, configure Key Vault access policies, define key rotation schedules, and document your cryptographic key management plan.",
    summary:
      "Microsoft provides Azure Key Vault in GCC High with hardware security modules for managing encryption keys. You must set up your key management procedures — who can access keys, how often they rotate, and what happens when a key is compromised. Document these decisions in a key management plan.",
  },

  "3.13.11": {
    tier: "Shared",
    services: ["Azure Networking", "Intune"],
    microsoftCovers:
      "GCC High services use FIPS-validated cryptographic modules for platform encryption, and Azure Key Vault provides FIPS 140-2 Level 2 validated HSMs. BitLocker provides FIPS-compliant disk encryption.",
    customerOwns:
      "Enable FIPS mode on endpoints via Intune policy, verify that any third-party tools also use FIPS-validated cryptography, and document your FIPS compliance posture.",
    summary:
      "Microsoft uses FIPS-validated encryption across GCC High and provides BitLocker and Key Vault with validated crypto modules. You need to enable FIPS mode on your devices through Intune and make sure any other encryption tools you use are also FIPS-validated — no consumer-grade encryption allowed.",
  },

  "3.13.12": {
    tier: "Shared",
    services: ["Intune", "Entra ID", "Defender"],
    microsoftCovers:
      "GCC High provides Intune device configuration profiles, Defender endpoint controls, and Teams admin policies to manage collaborative computing devices like cameras and microphones.",
    customerOwns:
      "Configure Intune policies to disable remote activation of cameras, microphones, and other collaborative devices, and set Teams meeting policies to control peripheral access.",
    summary:
      "Microsoft provides Intune and Teams admin controls in GCC High to manage cameras, microphones, and similar devices. You must configure policies that prevent remote activation of these peripherals — so nobody can silently turn on a camera or mic without the user knowing.",
  },

  "3.13.13": {
    tier: "Shared",
    services: ["Sentinel", "Defender", "Intune"],
    microsoftCovers:
      "GCC High provides Sentinel analytics, web application firewall rules, Defender SmartScreen, and Intune app protection to detect and control mobile code execution.",
    customerOwns:
      "Configure Defender and Intune policies to control which scripts, macros, and active content can execute, and monitor Sentinel for mobile code anomalies.",
    summary:
      "Microsoft provides Defender, Sentinel, and Intune in GCC High to help detect and block dangerous scripts and active content. You must configure which types of mobile code — macros, JavaScript, ActiveX — are allowed or blocked, and monitor alerts for anything suspicious.",
  },

  "3.13.14": {
    tier: "Shared",
    services: ["Sentinel", "Entra ID", "Intune"],
    microsoftCovers:
      "GCC High provides Teams as the managed VoIP platform with built-in encryption, Sentinel monitoring for call anomalies, and Entra ID authentication for voice services.",
    customerOwns:
      "Configure Teams voice policies, enable call recording and monitoring where required, restrict unauthorized VoIP applications, and review Sentinel alerts for voice traffic anomalies.",
    summary:
      "Microsoft provides Teams with encrypted VoIP and Sentinel monitoring in GCC High. You need to set up Teams voice policies, block unauthorized calling apps, and decide whether call recording or monitoring is required for your CUI environment. Review Sentinel for unusual voice traffic patterns.",
  },

  "3.13.15": {
    tier: "Shared",
    services: ["Entra ID", "Azure Networking", "Intune"],
    microsoftCovers:
      "GCC High provides TLS/SSL certificate management, Entra ID token-based session authentication, and ExpressRoute private peering to protect communication session authenticity.",
    customerOwns:
      "Configure Conditional Access to enforce strong session authentication, manage certificates for any custom applications, and verify TLS enforcement across your services.",
    summary:
      "Microsoft provides Entra ID session tokens, TLS certificates, and Key Vault in GCC High to prove that communications are authentic. You need to configure Conditional Access for strong session controls and make sure all your apps and services enforce TLS — no unencrypted sessions allowed.",
  },

  "3.13.16": {
    tier: "Shared",
    services: ["Purview", "Intune", "Azure Networking"],
    microsoftCovers:
      "GCC High provides BitLocker for disk encryption, Azure Key Vault for key management, Purview sensitivity labels for file-level protection, and service-level encryption for data at rest.",
    customerOwns:
      "Enable BitLocker via Intune, configure Purview sensitivity labels for CUI, define Key Vault policies for encryption keys, and verify all CUI storage locations use encryption at rest.",
    summary:
      "Microsoft provides BitLocker, Key Vault, and Purview in GCC High to encrypt data at rest. You must turn on BitLocker through Intune, apply sensitivity labels to CUI files, and confirm that every place you store CUI — SharePoint, email, devices — has encryption enabled.",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 3.14 — SYSTEM & INFORMATION INTEGRITY (7 controls)
  // ═══════════════════════════════════════════════════════════════════════════

  "3.14.1": {
    tier: "Shared",
    services: ["Sentinel", "Intune", "Defender"],
    microsoftCovers:
      "GCC High provides Sentinel for vulnerability aggregation, Intune for patch deployment, Defender for Endpoint vulnerability management, and Defender for Cloud security posture assessments.",
    customerOwns:
      "Define patching timelines, configure Intune update rings, review Defender vulnerability reports, and remediate identified system flaws within your defined SLAs.",
    summary:
      "Microsoft provides Sentinel, Intune, and Defender in GCC High to find and push patches for system flaws. You must decide how fast patches get applied, configure update schedules in Intune, and actually fix the vulnerabilities Defender finds — the tools flag problems but you close them.",
  },

  "3.14.2": {
    tier: "Shared",
    services: ["Defender", "Intune"],
    microsoftCovers:
      "GCC High provides Defender for Endpoint with real-time antimalware, Defender for Office 365 with safe attachments and safe links, and Defender for Cloud Apps for SaaS threat protection.",
    customerOwns:
      "Configure Defender antimalware policies, enable safe attachments and safe links in Defender for Office 365, set Intune compliance policies requiring active protection, and define your malware response procedures.",
    summary:
      "Microsoft provides Defender antimalware across endpoints, email, and cloud apps in GCC High. You need to configure the protection policies — turn on safe attachments, safe links, and real-time scanning — and have a plan for what happens when malware is actually detected.",
  },

  "3.14.3": {
    tier: "Shared",
    services: ["Defender", "Sentinel"],
    microsoftCovers:
      "GCC High provides Defender XDR for correlated security alerts, Defender for Endpoint and Office 365 for threat detection, and Defender for Cloud for posture alerts across the environment.",
    customerOwns:
      "Configure alert policies and severity thresholds, establish monitoring schedules, assign staff to review and triage security alerts, and define escalation procedures for critical findings.",
    summary:
      "Microsoft provides Defender XDR and multiple Defender products in GCC High that generate security alerts and advisories. You must assign someone to actually monitor those alerts, set up severity thresholds, and define who gets called when something critical shows up — alerts without eyeballs are useless.",
  },

  "3.14.4": {
    tier: "Shared",
    services: ["Defender", "Intune"],
    microsoftCovers:
      "GCC High provides automatic signature and definition updates for Defender for Endpoint, Defender for Office 365, Defender SmartScreen, and Defender for Cloud Apps.",
    customerOwns:
      "Verify that Defender definition updates are applying successfully, configure Intune to enforce update compliance, and monitor for any devices with outdated protection signatures.",
    summary:
      "Microsoft automatically updates malware definitions across Defender products in GCC High. Your job is to verify those updates are actually reaching all your devices — check Intune compliance reports and investigate any machines that fall behind on signature updates.",
  },

  "3.14.5": {
    tier: "Shared",
    services: ["Defender", "Sentinel", "Entra ID"],
    microsoftCovers:
      "GCC High provides Defender for Endpoint periodic and real-time scanning, Sentinel scheduled analytics rules, Entra ID risk-based sign-in detection, and Defender for Cloud continuous security assessments.",
    customerOwns:
      "Configure scan schedules in Defender, enable Sentinel analytics rules, set up Entra ID Identity Protection policies, and define the frequency of organization-wide security scans.",
    summary:
      "Microsoft provides scanning tools in GCC High — Defender scans endpoints, Sentinel runs analytics, and Entra ID checks for risky sign-ins. You need to set the scan schedules, enable the analytics rules, and decide how often your organization runs full security sweeps beyond the real-time monitoring.",
  },

  "3.14.6": {
    tier: "Shared",
    services: ["Sentinel", "Defender", "Azure Networking"],
    microsoftCovers:
      "GCC High provides Sentinel SIEM for attack detection, Defender for Identity for lateral movement detection, Azure Firewall threat intelligence, and Defender for IoT for network anomaly detection.",
    customerOwns:
      "Configure Sentinel detection rules and workbooks, tune Defender for Identity alerts, define what constitutes an attack for your environment, and establish incident response procedures.",
    summary:
      "Microsoft provides Sentinel SIEM, Defender for Identity, and Firewall threat intelligence in GCC High to detect attacks on your systems. You must configure the detection rules, tune alert thresholds so you catch real threats without drowning in noise, and have an incident response plan ready.",
  },

  "3.14.7": {
    tier: "Shared",
    services: ["Sentinel", "Defender", "Entra ID"],
    microsoftCovers:
      "GCC High provides Sentinel user and entity behavior analytics, Defender for Cloud Apps shadow IT discovery, Defender for Identity anomaly detection, and Entra ID risky user and sign-in reports.",
    customerOwns:
      "Define what constitutes unauthorized use in your organization, configure UEBA rules in Sentinel, review Entra ID risk reports, and investigate flagged user behavior.",
    summary:
      "Microsoft provides behavior analytics in Sentinel, shadow IT detection in Defender, and risky user reports in Entra ID within GCC High. You must define what 'unauthorized use' looks like for your organization, configure the detection rules, and investigate when the tools flag suspicious user behavior.",
  },
};

/**
 * Check if a control has CRM data.
 */
export function hasCrm(controlId: string): boolean {
  return controlId in crmData;
}

/**
 * Get CRM data for a control, or undefined if none exists.
 */
export function getCrm(controlId: string): ControlCrm | undefined {
  return crmData[controlId];
}

/**
 * Roll up tier counts for a set of control IDs (typically one domain).
 */
export function getDomainCrmCounts(controlIds: string[]): {
  inherited: number;
  shared: number;
  company: number;
} {
  const counts = { inherited: 0, shared: 0, company: 0 };
  for (const id of controlIds) {
    const entry = crmData[id];
    if (!entry) continue;
    switch (entry.tier) {
      case "Inherited":
        counts.inherited++;
        break;
      case "Shared":
        counts.shared++;
        break;
      case "Company":
        counts.company++;
        break;
    }
  }
  return counts;
}
