/**
 * Customer Responsibility Matrix (CRM) for CMMC Level 2 — GCC High / M365 G5
 *
 * Defines the shared-responsibility model between Microsoft and the customer
 * for each NIST SP 800-171 Rev 2 control.
 *
 * Tier sources:
 *   - "Inherited"  = Microsoft GCC High infrastructure; explicit placemat value
 *   - "Shared"     = Microsoft provides tooling, customer must configure/operate
 *   - "Company"    = Entirely customer-owned (no significant MS tooling)
 *
 * Controls marked (#N/A in placemat) were assigned "Shared" based on product
 * evidence: Microsoft provides the capability in GCC High but the customer
 * must configure, monitor, and operate it.
 *
 * Generated by: Policy or Config enrichment pipeline
 * Integration date: 2026-03-18
 */

export type ResponsibilityTier = "Inherited" | "Shared" | "Company";

export interface CrmEntry {
  tier: ResponsibilityTier;
  /** Simplified admin-center-level Microsoft service names (max 4-5) */
  services: string[];
  /** What Microsoft covers in GCC High */
  microsoftCovers: string;
  /** What the customer organization must do */
  customerOwns: string;
  /** Plain-English popover text for non-technical business owners (~40-60 words) */
  summary: string;
}

export const customerResponsibility: Record<string, CrmEntry> = {
  // ═══════════════════════════════════════════════════════════════════════════
  // 3.13 — SYSTEM & COMMUNICATIONS PROTECTION (16 controls)
  // ═══════════════════════════════════════════════════════════════════════════

  "3.13.1": {
    tier: "Inherited",
    services: ["Azure Networking", "Sentinel"],
    microsoftCovers:
      "GCC High provides boundary monitoring at the platform level through Azure Firewall, network security groups, and built-in DDoS protection across all tenant traffic.",
    customerOwns:
      "Review Microsoft-provided boundary monitoring logs in Sentinel and escalate anomalies through your incident response process.",
    summary:
      "Microsoft monitors all network boundaries in GCC High at the infrastructure level — this is one of the few controls they fully own. Your team should still review Sentinel dashboards periodically to stay aware of boundary events, but the heavy lifting is handled by the platform.",
  },

  "3.13.2": {
    tier: "Shared",
    services: ["Azure Networking", "Entra ID", "Defender"],
    microsoftCovers:
      "GCC High provides security architecture building blocks including network segmentation, zero-trust identity via Entra ID, and Defender security baselines.",
    customerOwns:
      "Design and document your security architecture, including network topology decisions, trust boundaries, and how CUI flows through your environment.",
    summary:
      "Microsoft provides the architectural building blocks in GCC High — network segmentation, identity management, and security baselines. Your job is to design how those pieces fit together for your business and document your architecture so an assessor can see the big picture.",
  },

  "3.13.3": {
    tier: "Shared",
    services: ["Entra ID", "Intune"],
    microsoftCovers:
      "GCC High provides Privileged Identity Management (PIM), Conditional Access, and role-based access control to separate administrative functions from standard user access.",
    customerOwns:
      "Configure PIM roles, enforce Conditional Access policies that restrict admin portals, and ensure day-to-day users cannot access management interfaces.",
    summary:
      "Microsoft provides Entra ID PIM and Conditional Access in GCC High to keep admin functions separate from regular user access. You need to configure those roles and policies so your admins use elevated access only when needed and normal users never see management consoles.",
  },

  "3.13.4": {
    tier: "Shared",
    services: ["Azure Networking", "Intune", "Defender", "Purview"],
    microsoftCovers:
      "GCC High provides network security groups, web application firewalls, Defender for Office 365, and Purview data loss prevention to control information flow.",
    customerOwns:
      "Define and enforce DLP policies in Purview, configure NSG and WAF rules, and set Intune device compliance policies to prevent unauthorized data transfers.",
    summary:
      "Microsoft provides DLP tools in Purview, network firewalls, and Defender in GCC High to help block unauthorized data movement. You must set up the DLP rules, configure firewall policies, and define what counts as unauthorized transfer for your CUI.",
  },

  "3.13.5": {
    tier: "Inherited",
    services: ["Azure Networking"],
    microsoftCovers:
      "GCC High infrastructure implements network segmentation with publicly accessible components isolated in separate subnetworks using Azure virtual networks, load balancers, and NSGs.",
    customerOwns:
      "Verify your Azure network topology places any public-facing resources in isolated subnets and review Microsoft's shared responsibility documentation for your deployment.",
    summary:
      "Microsoft handles network segmentation for public-facing components at the GCC High infrastructure level — another control they largely own. If you deploy any public-facing Azure resources, confirm they sit in properly isolated subnets, but the platform architecture does the heavy lifting.",
  },

  "3.13.6": {
    tier: "Shared",
    services: ["Azure Networking", "Intune", "Defender"],
    microsoftCovers:
      "GCC High provides Azure Firewall with default-deny capability, NSGs, and Defender for IoT to enforce network traffic restrictions at multiple layers.",
    customerOwns:
      "Configure Azure Firewall and NSG rules to default-deny all inbound and outbound traffic, then create explicit allow rules only for approved traffic flows.",
    summary:
      "Microsoft provides Azure Firewall and NSGs in GCC High that support deny-by-default network rules. You need to actually configure those firewalls to block everything by default and only allow the specific traffic your business requires — no open-by-default shortcuts.",
  },

  "3.13.7": {
    tier: "Shared",
    services: ["Azure Networking", "Entra ID", "Intune"],
    microsoftCovers:
      "GCC High provides Azure Firewall forced tunneling, Entra ID Conditional Access, and Azure Virtual Desktop to route all remote traffic through controlled gateways.",
    customerOwns:
      "Configure VPN and Conditional Access policies to prevent split tunneling, ensuring all remote user traffic routes through your organization's security stack.",
    summary:
      "Microsoft provides forced tunneling and Conditional Access in GCC High so remote workers' traffic goes through your security controls. You must configure VPN policies and Conditional Access rules to block split tunneling — meaning no direct internet access that bypasses your firewalls.",
  },

  "3.13.8": {
    tier: "Shared",
    services: ["Purview", "Intune", "Azure Networking"],
    microsoftCovers:
      "GCC High provides Office Message Encryption, TLS for data in transit, Azure Key Vault for key management, and ExpressRoute for private connectivity.",
    customerOwns:
      "Enable and enforce encryption policies for email and file transfers containing CUI, configure Intune to require encrypted connections, and define which data requires encryption in transit.",
    summary:
      "Microsoft provides encryption tools in GCC High — message encryption, TLS connections, and Key Vault. You need to turn on encryption policies for emails and files that contain CUI, configure devices to require secure connections, and make sure nothing sensitive travels unencrypted.",
  },

  "3.13.9": {
    tier: "Shared",
    services: ["Entra ID", "Azure Networking", "Intune"],
    microsoftCovers:
      "GCC High provides session timeout capabilities in Entra ID, Azure VPN Gateway idle disconnect, and Intune device compliance session controls.",
    customerOwns:
      "Configure session timeout policies in Entra ID Conditional Access, set VPN idle disconnect timers, and define Intune compliance policies for session termination.",
    summary:
      "Microsoft provides session timeout settings in Entra ID and VPN Gateway in GCC High. You need to configure how long idle sessions last before they disconnect — set timeout values in Conditional Access and VPN policies so abandoned connections don't stay open indefinitely.",
  },

  "3.13.10": {
    tier: "Shared",
    services: ["Azure Networking", "Purview"],
    microsoftCovers:
      "GCC High provides Azure Key Vault for centralized cryptographic key lifecycle management including generation, storage, rotation, and revocation with FIPS 140-2 Level 2 validated HSMs.",
    customerOwns:
      "Establish key management procedures, configure Key Vault access policies, define key rotation schedules, and document your cryptographic key management plan.",
    summary:
      "Microsoft provides Azure Key Vault in GCC High with hardware security modules for managing encryption keys. You must set up your key management procedures — who can access keys, how often they rotate, and what happens when a key is compromised. Document these decisions in a key management plan.",
  },

  "3.13.11": {
    tier: "Shared",
    services: ["Azure Networking", "Intune"],
    microsoftCovers:
      "GCC High services use FIPS-validated cryptographic modules for platform encryption, and Azure Key Vault provides FIPS 140-2 Level 2 validated HSMs. BitLocker provides FIPS-compliant disk encryption.",
    customerOwns:
      "Enable FIPS mode on endpoints via Intune policy, verify that any third-party tools also use FIPS-validated cryptography, and document your FIPS compliance posture.",
    summary:
      "Microsoft uses FIPS-validated encryption across GCC High and provides BitLocker and Key Vault with validated crypto modules. You need to enable FIPS mode on your devices through Intune and make sure any other encryption tools you use are also FIPS-validated — no consumer-grade encryption allowed.",
  },

  "3.13.12": {
    tier: "Shared",
    services: ["Intune", "Entra ID", "Defender"],
    microsoftCovers:
      "GCC High provides Intune device configuration profiles, Defender endpoint controls, and Teams admin policies to manage collaborative computing devices like cameras and microphones.",
    customerOwns:
      "Configure Intune policies to disable remote activation of cameras, microphones, and other collaborative devices, and set Teams meeting policies to control peripheral access.",
    summary:
      "Microsoft provides Intune and Teams admin controls in GCC High to manage cameras, microphones, and similar devices. You must configure policies that prevent remote activation of these peripherals — so nobody can silently turn on a camera or mic without the user knowing.",
  },

  "3.13.13": {
    tier: "Shared",
    services: ["Sentinel", "Defender", "Intune"],
    microsoftCovers:
      "GCC High provides Sentinel analytics, web application firewall rules, Defender SmartScreen, and Intune app protection to detect and control mobile code execution.",
    customerOwns:
      "Configure Defender and Intune policies to control which scripts, macros, and active content can execute, and monitor Sentinel for mobile code anomalies.",
    summary:
      "Microsoft provides Defender, Sentinel, and Intune in GCC High to help detect and block dangerous scripts and active content. You must configure which types of mobile code — macros, JavaScript, ActiveX — are allowed or blocked, and monitor alerts for anything suspicious.",
  },

  "3.13.14": {
    tier: "Shared",
    services: ["Sentinel", "Entra ID", "Intune"],
    microsoftCovers:
      "GCC High provides Teams as the managed VoIP platform with built-in encryption, Sentinel monitoring for call anomalies, and Entra ID authentication for voice services.",
    customerOwns:
      "Configure Teams voice policies, enable call recording and monitoring where required, restrict unauthorized VoIP applications, and review Sentinel alerts for voice traffic anomalies.",
    summary:
      "Microsoft provides Teams with encrypted VoIP and Sentinel monitoring in GCC High. You need to set up Teams voice policies, block unauthorized calling apps, and decide whether call recording or monitoring is required for your CUI environment. Review Sentinel for unusual voice traffic patterns.",
  },

  "3.13.15": {
    tier: "Shared",
    services: ["Entra ID", "Azure Networking", "Intune"],
    microsoftCovers:
      "GCC High provides TLS/SSL certificate management, Entra ID token-based session authentication, and ExpressRoute private peering to protect communication session authenticity.",
    customerOwns:
      "Configure Conditional Access to enforce strong session authentication, manage certificates for any custom applications, and verify TLS enforcement across your services.",
    summary:
      "Microsoft provides Entra ID session tokens, TLS certificates, and Key Vault in GCC High to prove that communications are authentic. You need to configure Conditional Access for strong session controls and make sure all your apps and services enforce TLS — no unencrypted sessions allowed.",
  },

  "3.13.16": {
    tier: "Shared",
    services: ["Purview", "Intune", "Azure Networking"],
    microsoftCovers:
      "GCC High provides BitLocker for disk encryption, Azure Key Vault for key management, Purview sensitivity labels for file-level protection, and service-level encryption for data at rest.",
    customerOwns:
      "Enable BitLocker via Intune, configure Purview sensitivity labels for CUI, define Key Vault policies for encryption keys, and verify all CUI storage locations use encryption at rest.",
    summary:
      "Microsoft provides BitLocker, Key Vault, and Purview in GCC High to encrypt data at rest. You must turn on BitLocker through Intune, apply sensitivity labels to CUI files, and confirm that every place you store CUI — SharePoint, email, devices — has encryption enabled.",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 3.14 — SYSTEM & INFORMATION INTEGRITY (7 controls)
  // ═══════════════════════════════════════════════════════════════════════════

  "3.14.1": {
    tier: "Shared",
    services: ["Sentinel", "Intune", "Defender"],
    microsoftCovers:
      "GCC High provides Sentinel for vulnerability aggregation, Intune for patch deployment, Defender for Endpoint vulnerability management, and Defender for Cloud security posture assessments.",
    customerOwns:
      "Define patching timelines, configure Intune update rings, review Defender vulnerability reports, and remediate identified system flaws within your defined SLAs.",
    summary:
      "Microsoft provides Sentinel, Intune, and Defender in GCC High to find and push patches for system flaws. You must decide how fast patches get applied, configure update schedules in Intune, and actually fix the vulnerabilities Defender finds — the tools flag problems but you close them.",
  },

  "3.14.2": {
    tier: "Shared",
    services: ["Defender", "Intune"],
    microsoftCovers:
      "GCC High provides Defender for Endpoint with real-time antimalware, Defender for Office 365 with safe attachments and safe links, and Defender for Cloud Apps for SaaS threat protection.",
    customerOwns:
      "Configure Defender antimalware policies, enable safe attachments and safe links in Defender for Office 365, set Intune compliance policies requiring active protection, and define your malware response procedures.",
    summary:
      "Microsoft provides Defender antimalware across endpoints, email, and cloud apps in GCC High. You need to configure the protection policies — turn on safe attachments, safe links, and real-time scanning — and have a plan for what happens when malware is actually detected.",
  },

  "3.14.3": {
    tier: "Shared",
    services: ["Defender", "Sentinel"],
    microsoftCovers:
      "GCC High provides Defender XDR for correlated security alerts, Defender for Endpoint and Office 365 for threat detection, and Defender for Cloud for posture alerts across the environment.",
    customerOwns:
      "Configure alert policies and severity thresholds, establish monitoring schedules, assign staff to review and triage security alerts, and define escalation procedures for critical findings.",
    summary:
      "Microsoft provides Defender XDR and multiple Defender products in GCC High that generate security alerts and advisories. You must assign someone to actually monitor those alerts, set up severity thresholds, and define who gets called when something critical shows up — alerts without eyeballs are useless.",
  },

  "3.14.4": {
    tier: "Shared",
    services: ["Defender", "Intune"],
    microsoftCovers:
      "GCC High provides automatic signature and definition updates for Defender for Endpoint, Defender for Office 365, Defender SmartScreen, and Defender for Cloud Apps.",
    customerOwns:
      "Verify that Defender definition updates are applying successfully, configure Intune to enforce update compliance, and monitor for any devices with outdated protection signatures.",
    summary:
      "Microsoft automatically updates malware definitions across Defender products in GCC High. Your job is to verify those updates are actually reaching all your devices — check Intune compliance reports and investigate any machines that fall behind on signature updates.",
  },

  "3.14.5": {
    tier: "Shared",
    services: ["Defender", "Sentinel", "Entra ID"],
    microsoftCovers:
      "GCC High provides Defender for Endpoint periodic and real-time scanning, Sentinel scheduled analytics rules, Entra ID risk-based sign-in detection, and Defender for Cloud continuous security assessments.",
    customerOwns:
      "Configure scan schedules in Defender, enable Sentinel analytics rules, set up Entra ID Identity Protection policies, and define the frequency of organization-wide security scans.",
    summary:
      "Microsoft provides scanning tools in GCC High — Defender scans endpoints, Sentinel runs analytics, and Entra ID checks for risky sign-ins. You need to set the scan schedules, enable the analytics rules, and decide how often your organization runs full security sweeps beyond the real-time monitoring.",
  },

  "3.14.6": {
    tier: "Shared",
    services: ["Sentinel", "Defender", "Azure Networking"],
    microsoftCovers:
      "GCC High provides Sentinel SIEM for attack detection, Defender for Identity for lateral movement detection, Azure Firewall threat intelligence, and Defender for IoT for network anomaly detection.",
    customerOwns:
      "Configure Sentinel detection rules and workbooks, tune Defender for Identity alerts, define what constitutes an attack for your environment, and establish incident response procedures.",
    summary:
      "Microsoft provides Sentinel SIEM, Defender for Identity, and Firewall threat intelligence in GCC High to detect attacks on your systems. You must configure the detection rules, tune alert thresholds so you catch real threats without drowning in noise, and have an incident response plan ready.",
  },

  "3.14.7": {
    tier: "Shared",
    services: ["Sentinel", "Defender", "Entra ID"],
    microsoftCovers:
      "GCC High provides Sentinel user and entity behavior analytics, Defender for Cloud Apps shadow IT discovery, Defender for Identity anomaly detection, and Entra ID risky user and sign-in reports.",
    customerOwns:
      "Define what constitutes unauthorized use in your organization, configure UEBA rules in Sentinel, review Entra ID risk reports, and investigate flagged user behavior.",
    summary:
      "Microsoft provides behavior analytics in Sentinel, shadow IT detection in Defender, and risky user reports in Entra ID within GCC High. You must define what 'unauthorized use' looks like for your organization, configure the detection rules, and investigate when the tools flag suspicious user behavior.",
  },
};
