/**
 * DoD Organization-Defined Parameters (ODPs) for NIST SP 800-171 Rev 3
 * Source: DoD ODP Memo, signed 2025-04-10 by David W. McKeown
 *
 * COMPLETE: All 40 R2-mapped controls with ODP values.
 * First 7 controls have detailed R3 statement text; remaining 33 have values only.
 * Keyed by Rev 2 control ID (3.x.x) for compatibility with the app's control data.
 *
 * Generated by: Policy or Config enrichment pipeline
 * Integration date: 2026-03-15
 */

export interface OdpEntry {
  /** ODP identifier from the memo, e.g. "03.01.01.f.02" */
  odpId: string;
  /** The assignment placeholder text */
  assignmentText: string;
  /** The DoD-defined value */
  value: string;
}

export interface ControlOdp {
  /** Rev 3 control title from the ODP memo */
  rev3Title: string;
  /** Rev 3 control statement items (lettered sub-requirements) */
  statement: string[];
  /** Related 800-53 controls */
  relatedControls: string[];
  /** The ODP values for this control */
  odps: OdpEntry[];
}

/**
 * Map of Rev 2 control ID -> ODP data.
 * All 40 controls that have ODPs are included.
 */
export const odpData: Record<string, ControlOdp> = {
  // ── Original 7 controls with detailed R3 statement text ──────────────────────

  // ── Access Control ──────────────────────────────────────────────

  "3.1.1": {
    rev3Title: "System Account Management",
    statement: [
      "a. Define the types of system accounts allowed and prohibited.",
      "b. Create, enable, modify, disable, and remove system accounts in accordance with policy, procedures, prerequisites, and criteria.",
      "c. Specify: (1) Authorized users of the system, (2) Group and role membership, and (3) Access authorizations (i.e., privileges) for each account.",
      "d. Authorize access to the system based on: (1) A valid access authorization and (2) Intended system usage.",
      "e. Monitor the use of system accounts.",
      "f. Disable system accounts when: (1) The accounts have expired, (2) The accounts have been inactive for [ODP: time period], (3) The accounts are no longer associated with a user or individual, (4) The accounts are in violation of organizational policy, or (5) Significant risks associated with individuals are discovered.",
      "g. Notify account managers and designated personnel or roles within [ODP: time periods] when accounts are no longer required, when users are terminated or transferred, and when system usage or need-to-know changes.",
      "h. Require that users log out of the system after: (1) [ODP: time period] of expected inactivity, or (2) When [ODP: circumstances].",
    ],
    relatedControls: ["AC-02", "AC-02(03)", "AC-02(05)", "AC-02(13)"],
    odps: [
      {
        odpId: "03.01.01.f.02",
        assignmentText: "organization-defined time period",
        value: "at most 90 days",
      },
      {
        odpId: "03.01.01.g.01",
        assignmentText: "organization-defined time period",
        value: "24 hours",
      },
      {
        odpId: "03.01.01.g.02",
        assignmentText: "organization-defined time period",
        value: "24 hours",
      },
      {
        odpId: "03.01.01.g.03",
        assignmentText: "organization-defined time period",
        value: "24 hours",
      },
      {
        odpId: "03.01.01.h.01",
        assignmentText: "organization-defined time period",
        value: "at most 24 hours",
      },
      {
        odpId: "03.01.01.h.02",
        assignmentText: "organization-defined circumstances",
        value: "the work period ends, for privileged users at a minimum",
      },
    ],
  },

  "3.1.5": {
    rev3Title: "System Access Authorization",
    statement: [
      "a. Allow only authorized system access for users (or processes acting on behalf of users) that is necessary to accomplish assigned organizational tasks.",
      "b. Authorize access to: (1) [ODP: security functions], and (2) [ODP: security-relevant information].",
      "c. Review the privileges assigned to roles or classes of users [ODP: frequency] to validate the need for such privileges.",
      "d. Reassign or remove privileges, as necessary.",
    ],
    relatedControls: ["AC-06", "AC-06(01)", "AC-06(07)", "AU-09(04)"],
    odps: [
      {
        odpId: "03.01.05.b.01",
        assignmentText: "organization-defined security functions",
        value:
          "at a minimum and if applicable: establishing system accounts and assigning privileges, configuring access authorizations, configuring settings for events to be audited, establishing vulnerability scanning parameters, establishing intrusion detection parameters, and managing audit information",
      },
      {
        odpId: "03.01.05.b.02",
        assignmentText: "organization-defined security-relevant information",
        value:
          "at a minimum and if applicable: threat and vulnerability information, filtering rules for routers or firewalls, configuration parameters for security services, cryptographic key management information, security architecture, access control lists, and audit information",
      },
      {
        odpId: "03.01.05.c",
        assignmentText: "organization-defined frequency",
        value: "at least every 12 months",
      },
    ],
  },

  "3.1.6": {
    rev3Title: "Privileged Account Management",
    statement: [
      "a. Restrict privileged accounts on the system to [ODP: personnel or roles].",
      "b. Require that users (or roles) with privileged accounts use non-privileged accounts when accessing non-security functions or non-security information.",
    ],
    relatedControls: ["AC-06(02)", "AC-06(05)"],
    odps: [
      {
        odpId: "03.01.06.a",
        assignmentText: "organization-defined personnel or roles",
        value: "only defined and authorized personnel or administrative roles",
      },
    ],
  },

  "3.1.8": {
    rev3Title: "Invalid Logon Attempts",
    statement: [
      "a. Enforce a limit of [ODP: number] consecutive invalid logon attempts by a user during a [ODP: time period].",
      "b. Automatically [ODP: action] when the maximum number of unsuccessful attempts is exceeded.",
    ],
    relatedControls: ["AC-07"],
    odps: [
      {
        odpId: "03.01.08.a.01",
        assignmentText: "organization-defined number",
        value: "at most five (5)",
      },
      {
        odpId: "03.01.08.a.02",
        assignmentText: "organization-defined time period",
        value: "period of five (5) minutes",
      },
      {
        odpId: "03.01.08.b",
        assignmentText: "organization-defined action",
        value:
          "lock the account or node for an at least 15-minute time period; lock the account or node until released by an administrator and notify a system administrator",
      },
    ],
  },

  "3.1.10": {
    rev3Title: "Device Lock",
    statement: [
      "a. Prevent access to the system by initiating a device lock after [ODP: time period] of inactivity; requiring the user to initiate a device lock before leaving the system unattended.",
      "b. Retain the device lock until the user reestablishes access using established identification and authentication procedures.",
      "c. Conceal, via the device lock, information previously visible on the display with a publicly viewable image.",
    ],
    relatedControls: ["AC-11", "AC-11(01)"],
    odps: [
      {
        odpId: "03.01.10.a",
        assignmentText: "organization-defined time period",
        value:
          'initiating a device lock after "at most 15 minutes" of inactivity and requiring the user to initiate a device lock before leaving the system unattended',
      },
    ],
  },

  "3.1.11": {
    rev3Title: "Session Termination",
    statement: [
      "Terminate a user session automatically after [ODP: conditions or trigger events requiring session disconnect].",
    ],
    relatedControls: ["AC-12"],
    odps: [
      {
        odpId: "03.01.11",
        assignmentText:
          "organization-defined conditions or trigger events requiring session disconnect",
        value:
          "a specified duration (maximum of 24 hours) of inactivity, misbehavior (end the session due to an attempted policy violation), and maintenance (terminate sessions to prevent issues with an upgrade or service outage)",
      },
    ],
  },

  "3.1.20": {
    rev3Title: "Use of External Systems",
    statement: [
      "a. Prohibit the use of external systems unless the systems are specifically authorized.",
      "b. Establish the following security requirements to be satisfied on external systems prior to allowing use of or access to those systems by authorized individuals: [ODP: security requirements].",
      "c. Permit authorized individuals to use external systems to access the organizational system or to process, store, or transmit CUI only after: (1) Verifying that the security requirements on the external systems as specified in the organization's system security plans have been satisfied, and (2) Retaining approved system connection or processing agreements with the organizational entities hosting the external systems.",
      "d. Restrict the use of organization-controlled portable storage devices by authorized individuals on external systems.",
    ],
    relatedControls: ["AC-20", "AC-20(01)", "AC-20(02)"],
    odps: [
      {
        odpId: "03.01.20.b",
        assignmentText: "organization-defined security requirements",
        value:
          "Guidance: Organizations establish specific terms and conditions for the use of external systems in accordance with organizational security policies and procedures. At a minimum, terms and conditions address the specific types of applications that can be accessed on organizational systems from external systems and the highest security category of information that can be processed, stored, or transmitted on external systems. If the terms and conditions with the owners of the external systems cannot be established, organizations may impose restrictions on organizational personnel using those external systems. If applicable, use NIST SP 800-47 as a guide for establishing information exchanges between organizations.",
      },
    ],
  },

  // ── Additional 33 controls from DoD ODP Memo ──────────────────────────────

  "3.2.1": {
    rev3Title: "Security Literacy Training",
    statement: [],
    relatedControls: [],
    odps: [
      {
        odpId: "3.2.1.odp.01",
        assignmentText: "Initial + recurring training frequency",
        value: "at least every 12 months",
      },
      {
        odpId: "3.2.1.odp.02",
        assignmentText: "Events triggering re-training",
        value: "significant or novel incidents, or significant changes to risks",
      },
      {
        odpId: "3.2.1.odp.03",
        assignmentText: "Update training content",
        value: "at least every 12 months",
      },
      {
        odpId: "3.2.1.odp.04",
        assignmentText: "Events triggering content update",
        value: "significant or novel incidents, or significant changes to risks",
      },
    ],
  },

  "3.2.2": {
    rev3Title: "Role-Based Security Training",
    statement: [],
    relatedControls: [],
    odps: [
      {
        odpId: "3.2.2.odp.01",
        assignmentText: "Recurring role-based training",
        value: "at least every 12 months",
      },
      {
        odpId: "3.2.2.odp.02",
        assignmentText: "Events triggering re-training",
        value: "significant or novel incidents, or significant changes to risks",
      },
      {
        odpId: "3.2.2.odp.03",
        assignmentText: "Update training content",
        value: "at least every 12 months",
      },
      {
        odpId: "3.2.2.odp.04",
        assignmentText: "Events triggering content update",
        value: "significant or novel incidents, or significant changes to risks",
      },
    ],
  },

  "3.3.1": {
    rev3Title: "Event Logging",
    statement: [],
    relatedControls: [],
    odps: [
      {
        odpId: "3.3.1.odp.01",
        assignmentText: "Event types for logging",
        value:
          "at a minimum — (1) Authentication events (logon/logoff), (2) File/Object events (create, access, delete, modify, permission/ownership changes), (3) Export/downloads to media, (4) Import/uploads from media, (5) User/Group management, (6) Privileged rights usage (policy/config changes), (7) Admin/root access, (8) Privilege escalation, (9) Audit log access, (10) System reboot/restart/shutdown, (11) Print to device, (12) Print to file, (13) Application initialization. See OMB 21-31 ML1.",
      },
      {
        odpId: "3.3.1.odp.02",
        assignmentText: "Review/update event types",
        value: "at least every 12 months and after significant incidents or changes to risks",
      },
    ],
  },

  "3.3.4": {
    rev3Title: "Audit Logging Process Failure",
    statement: [],
    relatedControls: [],
    odps: [
      {
        odpId: "3.3.4.odp.01",
        assignmentText: "Alert timeframe for audit failure",
        value: "near real time or as soon as practicable upon discovery",
      },
      {
        odpId: "3.3.4.odp.02",
        assignmentText: "Additional actions",
        value:
          "document the failure and resolution, troubleshoot, repair/restart the audit logging process, and report as incident if applicable",
      },
    ],
  },

  "3.3.5": {
    rev3Title: "Audit Record Review and Analysis",
    statement: [],
    relatedControls: [],
    odps: [
      {
        odpId: "3.3.5.odp.01",
        assignmentText: "Frequency of audit record review",
        value: "at least weekly",
      },
    ],
  },

  "3.3.7": {
    rev3Title: "Time Stamps for Audit Records",
    statement: [],
    relatedControls: [],
    odps: [
      {
        odpId: "3.3.7.odp.01",
        assignmentText: "Granularity of time measurement",
        value: "one (1) second or smaller",
      },
    ],
  },

  "3.4.1": {
    rev3Title: "Baseline Configuration",
    statement: [],
    relatedControls: [],
    odps: [
      {
        odpId: "3.4.1.odp.01",
        assignmentText: "Review/update baseline configuration",
        value:
          "at least every 12 months and after any significant incidents or significant changes",
      },
    ],
  },

  "3.4.2": {
    rev3Title: "Configuration Settings",
    statement: [],
    relatedControls: [],
    odps: [
      {
        odpId: "3.4.2.odp.01",
        assignmentText: "Configuration settings",
        value:
          "Apply NIST National Checklist Program (NCP) configurations (https://ncp.nist.gov/repository) and prevent remote devices from simultaneously establishing non-remote connections with organizational systems and communicating via unauthorized external connections. Document any deviations.",
      },
    ],
  },

  "3.4.6": {
    rev3Title: "System Configuration (Least Functionality)",
    statement: [],
    relatedControls: [],
    odps: [
      {
        odpId: "3.4.6.odp.01",
        assignmentText: "Functions/ports/protocols/connections/services to prohibit or restrict",
        value:
          "[Guidance] Limit component functionality to a single function per component where feasible. Remove unused software, disable unused ports/protocols. Employ network scanning, IDS/IPS, and endpoint protection to prevent use of prohibited functions.",
      },
      {
        odpId: "3.4.6.odp.02",
        assignmentText: "Review frequency",
        value:
          "at least every 12 months, when any system functions/ports/protocols/services change, and after significant incidents or changes to risks",
      },
    ],
  },

  "3.4.8": {
    rev3Title: "Software Execution Authorization",
    statement: [],
    relatedControls: [],
    odps: [
      {
        odpId: "3.4.8.odp.01",
        assignmentText: "Review/update authorized software list",
        value: "at least quarterly",
      },
    ],
  },

  "3.4.9": {
    rev3Title: "System Component Inventory",
    statement: [],
    relatedControls: [],
    odps: [
      {
        odpId: "3.4.9.odp.01",
        assignmentText: "Review/update system component inventory",
        value: "at least quarterly",
      },
    ],
  },

  "3.5.1": {
    rev3Title: "User Identification and Authentication",
    statement: [],
    relatedControls: [],
    odps: [
      {
        odpId: "3.5.1.odp.01",
        assignmentText: "Re-authentication required when",
        value:
          "roles, authenticators, or credentials change; security categories of systems change; execution of privileged functions occurs; and after session termination",
      },
    ],
  },

  "3.5.2": {
    rev3Title: "Device Identification and Authentication",
    statement: [],
    relatedControls: [],
    odps: [
      {
        odpId: "3.5.2.odp.01",
        assignmentText: "Devices requiring identification/authentication",
        value:
          "all devices for identification, where feasible for authentication, and document when not feasible",
      },
    ],
  },

  "3.5.5": {
    rev3Title: "Identifier Management",
    statement: [],
    relatedControls: [],
    odps: [
      {
        odpId: "3.5.5.odp.01",
        assignmentText: "Prevent identifier reuse for",
        value: "at least 10 years",
      },
      {
        odpId: "3.5.5.odp.02",
        assignmentText: "Identify individual status as",
        value:
          "privileged or non-privileged users; contractors, foreign nationals, and/or non-organizational users",
      },
    ],
  },

  "3.5.7": {
    rev3Title: "Password Management",
    statement: [],
    relatedControls: [],
    odps: [
      {
        odpId: "3.5.7.odp.01",
        assignmentText: "Update compromised password list",
        value: "at least quarterly",
      },
      {
        odpId: "3.5.7.odp.02",
        assignmentText: "Password composition/complexity",
        value:
          "(1) Minimum length of 16 characters. (2) Must not include user's account name or full name.",
      },
    ],
  },

  "3.5.10": {
    rev3Title: "Authenticator Management",
    statement: [],
    relatedControls: [],
    odps: [
      {
        odpId: "3.5.10.odp.01",
        assignmentText: "Change/refresh authenticators",
        value:
          "never for passwords where MFA is employed; at least every 5 years for hard tokens and identification badges; at least every 3 years for all other authenticators",
      },
      {
        odpId: "3.5.10.odp.02",
        assignmentText: "Events triggering authenticator change",
        value: "after a relevant security incident or any evidence of compromise or loss",
      },
    ],
  },

  "3.6.2": {
    rev3Title: "Incident Tracking and Reporting",
    statement: [],
    relatedControls: [],
    odps: [
      {
        odpId: "3.6.2.odp.01",
        assignmentText: "Report suspected incidents",
        value: "near real time or as soon as practicable upon discovery",
      },
      {
        odpId: "3.6.2.odp.02",
        assignmentText: "Report incident information to",
        value:
          "all applicable personnel and entities as specified by the contract, and in accordance with incident response plan notification procedures",
      },
    ],
  },

  "3.6.3": {
    rev3Title: "Incident Response Testing",
    statement: [],
    relatedControls: [],
    odps: [
      {
        odpId: "3.6.3.odp.01",
        assignmentText: "Test incident response capability",
        value: "at least every 12 months",
      },
    ],
  },

  "3.8.7": {
    rev3Title: "System Media Restrictions",
    statement: [],
    relatedControls: [],
    odps: [
      {
        odpId: "3.8.7.odp.01",
        assignmentText: "Types of system media to restrict/prohibit",
        value: "any removable media not managed by or on behalf of the organization",
      },
    ],
  },

  "3.9.1": {
    rev3Title: "Screening and Rescreening",
    statement: [],
    relatedControls: [],
    odps: [
      {
        odpId: "3.9.1.odp.01",
        assignmentText: "Conditions requiring rescreening",
        value:
          "when there is a significant incident, or change in status, related to an individual",
      },
    ],
  },

  "3.9.2": {
    rev3Title: "Employment Termination and Reassignment",
    statement: [],
    relatedControls: [],
    odps: [
      {
        odpId: "3.9.2.odp.01",
        assignmentText: "Disable system access upon termination",
        value: "within 4 hours",
      },
    ],
  },

  "3.10.1": {
    rev3Title: "Facility Access Control",
    statement: [],
    relatedControls: [],
    odps: [
      {
        odpId: "3.10.1.odp.01",
        assignmentText: "Review facility access list",
        value:
          "at least every 12 months, or when there are significant incidents or significant changes to risks",
      },
    ],
  },

  "3.10.2": {
    rev3Title: "Physical Access Monitoring and Review",
    statement: [],
    relatedControls: [],
    odps: [
      {
        odpId: "3.10.2.odp.01",
        assignmentText: "Review physical access logs",
        value: "at least every 45 days",
      },
      {
        odpId: "3.10.2.odp.02",
        assignmentText: "Events triggering review",
        value: "significant or novel incidents, or significant changes to risks",
      },
    ],
  },

  "3.10.6": {
    rev3Title: "Alternate Work Sites",
    statement: [],
    relatedControls: [],
    odps: [
      {
        odpId: "3.10.6.odp.01",
        assignmentText: "Security requirements at alternate work sites",
        value:
          "adequate security, comparable to organizational security requirements at the primary work site where practical, documented in policy, and covered by training",
      },
    ],
  },

  "3.11.1": {
    rev3Title: "Risk Assessment",
    statement: [],
    relatedControls: [],
    odps: [
      {
        odpId: "3.11.1.odp.01",
        assignmentText: "Update risk assessments",
        value:
          "at least every 12 months, or when there are significant incidents or significant changes to risks",
      },
    ],
  },

  "3.11.2": {
    rev3Title: "System Vulnerability Management",
    statement: [],
    relatedControls: [],
    odps: [
      {
        odpId: "3.11.2.odp.01",
        assignmentText: "Vulnerability scan frequency",
        value: "at least monthly, or when there are significant incidents or changes to risks",
      },
      {
        odpId: "3.11.2.odp.02",
        assignmentText: "Remediation timeframes",
        value:
          "30 days for high-risk (critical + high); 90 days for moderate-risk; 180 days for low-risk",
      },
      {
        odpId: "3.11.2.odp.03",
        assignmentText: "Update vulnerability scan definitions",
        value: "no more than 24 hours prior to running the scans",
      },
    ],
  },

  "3.12.1": {
    rev3Title: "Security Requirements Assessment",
    statement: [],
    relatedControls: [],
    odps: [
      {
        odpId: "3.12.1.odp.01",
        assignmentText: "Assess security requirements",
        value:
          "at least every 12 months, or when there are significant incidents or significant changes to risks",
      },
    ],
  },

  "3.13.9": {
    rev3Title: "Termination of Network Connections",
    statement: [],
    relatedControls: [],
    odps: [
      {
        odpId: "3.13.9.odp.01",
        assignmentText: "Terminate network connections after inactivity",
        value: "no longer than 15 minutes",
      },
    ],
  },

  "3.13.10": {
    rev3Title: "Cryptographic Key Management",
    statement: [],
    relatedControls: [],
    odps: [
      {
        odpId: "3.13.10.odp.01",
        assignmentText: "Key management requirements",
        value:
          "[Guidance] At a minimum, establish a policy and procedure in line with the latest Cryptographic key management guidance",
      },
    ],
  },

  "3.13.11": {
    rev3Title: "Cryptography for Confidentiality of CUI",
    statement: [],
    relatedControls: [],
    odps: [
      {
        odpId: "3.13.11.odp.01",
        assignmentText: "Types of cryptography",
        value:
          "FIPS Validated Cryptography (https://csrc.nist.gov/Projects/Cryptographic-Module-Validation-Program/Validated-Modules)",
      },
    ],
  },

  "3.13.12": {
    rev3Title: "Remote Activation of Collaborative Computing Devices",
    statement: [],
    relatedControls: [],
    odps: [
      {
        odpId: "3.13.12.odp.01",
        assignmentText: "Exceptions for remote activation",
        value:
          "only as enumerated and justified in the System Security Plan, only when there are no other options, and the remote activation is operationally critical",
      },
    ],
  },

  "3.14.1": {
    rev3Title: "System Flaw Remediation",
    statement: [],
    relatedControls: [],
    odps: [
      {
        odpId: "3.14.1.odp.01",
        assignmentText: "Install security updates",
        value:
          "30 days for high-risk (critical + high); 90 days for moderate-risk; 180 days for low-risk",
      },
    ],
  },

  "3.14.2": {
    rev3Title: "Malicious Code Protection",
    statement: [],
    relatedControls: [],
    odps: [
      {
        odpId: "3.14.2.odp.01",
        assignmentText: "System scan frequency",
        value: "at least weekly (plus real-time scans at endpoints)",
      },
    ],
  },

};

/**
 * Check if a control has ODP data.
 */
export function hasOdp(controlId: string): boolean {
  return controlId in odpData;
}

/**
 * Get ODP data for a control, or null if none exists.
 */
export function getOdp(controlId: string): ControlOdp | null {
  return odpData[controlId] ?? null;
}
